---

- name: systemd restart aptly REST api
  become: yes
  systemd:
    name: "{{ aptly_api_service_name }}"
    state: restarted
    daemon_reload: yes
  listen:
    - restart_aptly_api

- name: systemd restart nginx
  become: yes
  systemd:
    name: nginx
    state: restarted
    daemon_reload: yes
  listen:
    - restart_nginx
