---

- name: reload systemd
  become: yes
  command: systemctl daemon-reload

- name: restart nginx
  become: yes
  systemd:
    name: nginx
    state: restarted
    daemon_reload: yes

- name: restart spark-master
  become: yes
  systemd:
    name: spark-master
    state: restarted
    daemon_reload: yes
  when: spark_master_p
  listen: restart spark

- name: restart spark-slave
  become: yes
  systemd:
    name: spark-slave
    state: restarted
    daemon_reload: yes
  when: spark_worker_p
  listen: restart spark
