---

# FIXME this role probably should not have "openstack" in the name as it now supports terraform as well

_attached_openstack_tf_volume_device: "{{ (groups['tf_type_openstack_compute_volume_attach_v2'] | default([]) | map('extract', hostvars) | selectattr('tf_instance_id', 'equalto', tf_id | default('')) | list()) | json_query('[0].tf_device') }}"

# N.B. this is called pvs because it can be a list of PVs from which to create an LVM VG, but we only support one for now
attached_openstack_volume_pvs: "{{ _attached_openstack_tf_volume_device if tf_id is defined else (os_volumes | json_query('[0].device')) }}"

