# Variables that must be defined:
#   aptly_api_basic_auth_username:
#     (str) username to authenticate with for API access
#   aptly_api_basic_auth_password:
#     (str) password to authenticate with for API access

---

aptly_data_directory_location: "{{ ansible_env.HOME }}/.aptly"
aptly_aptly_binary_location: /usr/bin/aptly
aptly_publish_location: /var/aptly/public

# e.g.
# aptly_repositories:
#  - name: my-repository
#    options:
#      comment: some comment
#      distribution: jessie
#      component: main
aptly_repositories: []

aptly_apt_cache_valid_time: 3600

aptly_api_service_name: aptly-api
aptly_api_ssl_enabled: "{{ aptly_api_ssl_cert != '' and aptly_api_ssl_key != '' }}"
aptly_api_ssl_cert: ""
aptly_api_ssl_key: ""
aptly_api_ssl_cert_file_location: /etc/ssl.cert
aptly_api_ssl_key_file_location: /etc/ssl.key
aptly_api_password_file_location: /etc/aptly/aptly-rest-api.htpasswd
