---

- name: Install Consul agent
  become: yes
  include_role:
    name: wtsi-hgi.ansible-consul

- name: install dnsmasq
  become: yes
  apt:
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_time }}"
  with_items:
    - dnsmasq

- name: activate dnsmasq conf dir
  become: yes
  lineinfile:
    path: /etc/dnsmasq.conf
    regexp: 'conf-dir=/etc/dnsmasq.d$'
    line: 'conf-dir=/etc/dnsmasq.d'
  notify:
   - restart dnsmasq

- name: configure dnsmasq for .consul
  become: yes
  template:
    src: 10-consul.j2
    dest: /etc/dnsmasq.d/10-consul
  notify:
   - restart dnsmasq

- name: add consul dns search to resolvconf base
  become: yes
  lineinfile:
    path: /etc/resolvconf/resolv.conf.d/base
    state: present
    regexp: "^search node.{{ consul_datacenter }}.consul$"
    line: "search node.{{ consul_datacenter }}.consul"
  notify:
    - update resolvconf

