# Vault contains:
# consul_server_acl_master_token: xxxx
# consul_server_acl_token: xxxx

---

consul_server_acl_name: server_token

consul_bootstrap_expect: "{{ consul_servers | count }}"

consul_acl_master_token: "{{ consul_server_acl_master_token }}"
consul_acl_token: "{{ consul_server_acl_token }}"
consul_acl_default_policy: "deny"
consul_acl_datacenter: "{{ consul_datacenter }}"

consul_server_inventory_hostnames_wan: "{{ groups['consul-servers'] | default([]) | sort }}"
consul_server_advertise_addresses_wan: "{{ consul_server_inventory_hostnames_wan | map('extract', hostvars) | list() | map(attribute='consul_commoners_advertise_address') | list }}"
consul_servers_wan: "{{ consul_server_advertise_addresses_wan }}"
onsul_retry_join_wan: true

