# This script excepts the following Secret Variables to be defined in
# Gitlab project settings:
#  ANSIBLE_VAULT_PASSWORD
#  SSH_PRIVATE_KEY (e.g. "-----BEGIN RSA PRIVATE KEY-----
#                         ...
#                         -----END RSA PRIVATE KEY-----)"
#  GAMMA_OS_AUTH_URL
#  GAMMA_OS_USERNAME
#  GAMMA_OS_PASSWORD
#  DELTA_OS_AUTH_URL
#  DELTA_OS_USERNAME
#  DELTA_OS_PASSWORD
#  EMEDLAB_OS_AUTH_URL
#  EMEDLAB_OS_USERNAME
#  EMEDLAB_OS_PASSWORD
#  EMEDLAB_HTTP_PROXY
#  S3_ACCESS_KEY
#  S3_HOST
#  S3_SECRET_KEY
#  S3_IMAGE_BUCKET
#  TERRAGRUNT_LOCKS_AWS_ACCESS_KEY
#  TERRAGRUNT_LOCKS_AWS_SECRET_ACCESS
variables:
  GITHUB_REPO: "git@github.com:wtsi-hgi/hgi-systems.git"
  GITLAB_REPO: "git@gitlab.internal.sanger.ac.uk:hgi/hgi-systems.git"
  TF_LOG: "" # anything other than "" to trace

before_script:
  # Run ssh-agent (inside the build environment)
  - eval $(ssh-agent -s)

  # Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
  - ssh-add <(echo "$SSH_PRIVATE_KEY")

  # For Docker builds disable host key checking. Be aware that by adding that
  # you are suspectible to man-in-the-middle attacks.
  # WARNING: Use this only with the Docker executor, if you use it with shell
  # you will overwrite your user's SSH config.
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

stages:
  - prepare
  - refresh
  - plan
  - apply
  - commit
  - sync

version:
  stage: prepare
  tags:
    - docker
  image: mercury/gitlab-ci-git-push
  script:
    - git describe --tags --dirty --always --abbrev=8 > version.txt
  artifacts:
    paths:
      - "version.txt"

terraform-validate-production:
  stage: prepare
  tags:
   - docker
  image: quay.io/wtsi-hgi/taos:experimental
  script:
    - cd terraform/production && terraform validate

.production-gamma-hgi: &production-gamma-hgi-def
  variables:
    ENV: "production"
    REGION: "gamma-hgi"
  only:
    - master
    - production-gamma-hgi
  
.staging-gamma-hgi: &staging-gamma-hgi-def
  variables:
    ENV: "staging"
    REGION: "gamma-hgi"
  only:
    - develop
    - staging-gamma-hgi
  
.production-gamma-hgiarvados: &production-gamma-hgiarvados-def
  variables:
    ENV: "production"
    REGION: "gamma-hgiarvados"
  only:
    - master
    - production-gamma-hgiarvados
  
.staging-gamma-hgiarvados: &staging-gamma-hgiarvados-def
  variables:
    ENV: "staging"
    REGION: "gamma-hgiarvados"
  only:
    - develop
    - staging-gamma-hgiarvados
  
.production-delta-hgi: &production-delta-hgi-def
  variables:
    ENV: "production"
    REGION: "delta-hgi"
  only:
    - master
    - production-delta-hgi
  
.staging-delta-hgi: &staging-delta-hgi-def
  variables:
    ENV: "staging"
    REGION: "delta-hgi"
  only:
    - develop
    - staging-delta-hgi
  
.production-delta-hgiarvados: &production-delta-hgiarvados-def
  variables:
    ENV: "production"
    REGION: "delta-hgiarvados"
  only:
    - master
    - production-delta-hgiarvados
  
.staging-delta-hgiarvados: &staging-delta-hgiarvados-def
  variables:
    ENV: "staging"
    REGION: "delta-hgiarvados"
  only:
    - develop
    - staging-delta-hgiarvados
  
# .production-emedlab-arvados: &production-emedlab-arvados-def
#   variables:
#     ENV: "production"
#     REGION: "emedlab-arvados"
#   only:
#     - master
#     - production-emedlab-arvados
  
# .staging-emedlab-arvados: &staging-emedlab-arvados-def
#   variables:
#     ENV: "staging"
#     REGION: "emedlab-arvados"
#   only:
#     - develop
#     - staging-emedlab-arvados
  
.Openstack-vars-validate: &openstack-vars-validate-def
  stage: validate
  tags:
    - docker
  image: mercury/gitlab-ci-git-push
  script:
    - 'test -n "${OS_AUTH_URL}" || (echo "OS_AUTH_URL must be set!"; exit 1)'
    - 'test -n "${OS_USERNAME}" || test -n "${OS_USERID}" || (echo "OS_USERNAME or OS_USERID must be set!"; exit 1)'
    - 'test -n "${OS_PASSWORD}" || (echo "OS_PASSWORD must be set!"; exit 1)'
    - '((echo "${OS_AUTH_URL}" | grep -q "v3") && (test -n "${OS_DOMAIN_NAME}" || test -n "${OS_DOMAIN_ID}" || echo "WARNING: OS_DOMAIN_ID or OS_DOMAIN_NAME not set")) || exit 0'
  dependencies: []

.terraform-validate: &terraform-validate-def
  stage: validate
  tags:
    - docker
  image: quay.io/wtsi-hgi/taos:experimental
  script:
    - ci/terraform-validate.sh
  dependencies: []

terraform-refresh-production:
  stage: refresh
  tags:
    - docker
  image: quay.io/wtsi-hgi/taos:experimental
  script:
    - cd terraform/production && terraform refresh -backup=- && (terraform show -no-color > terraform.tfstate.txt)
  artifacts:
    paths:
      - terraform/production/terraform.tfstate
      - terraform/production/terraform.tfstate.txt
    when: always

terraform-plan-production:
  stage: plan
  tags:
    - docker
  image: quay.io/wtsi-hgi/taos:experimental
  script:
    - cd terraform/production && (terraform graph > plan.dot) && (dot -Tpng < plan.dot > plan.png) && terraform plan -input=false -out plan && (terraform show -no-color plan > plan.txt)
  artifacts:
    paths:
      - terraform/production/plan.dot
      - terraform/production/plan.png
      - terraform/production/plan
      - terraform/production/plan.txt
  dependencies:
    - terraform-refresh-production

terraform-apply-production:
  stage: apply
  tags:
    - docker
  image: quay.io/wtsi-hgi/taos:experimental
  script:
    - cd terraform/production && (terraform graph plan > apply.dot) && (dot -Tpng < apply.dot > apply.png) && terraform apply -input=false plan && (terraform output -json > output.json) && (terraform show -no-color > terraform.tfstate.txt)
  artifacts:
    paths:
      - terraform/production/apply.dot
      - terraform/production/apply.png
      - terraform/production/terraform.tfstate
      - terraform/production/output.json
      - terraform/production/terraform.tfstate.txt
    when: always
  dependencies:
    - terraform-plan-production

terraform-apply-staging-delta-hgiarvados:
  <<: *terraform-apply-def
  <<: *staging-delta-hgiarvados-def
  dependencies:
    - terraform-plan-staging-delta-hgiarvados

# terraform-apply-production-emedlab-arvados:
#   <<: *terraform-apply-def
#   <<: *production-emedlab-arvados-def
#   dependencies:
#     - terraform-plan-production-emedlab-arvados

# terraform-apply-staging-emedlab-arvados:
#   <<: *terraform-apply-def
#   <<: *staging-emedlab-arvados-def
#   dependencies:
#     - terraform-plan-staging-emedlab-arvados

github-sync:
  stage: sync
  tags:
    - docker
  image: quay.io/wtsi-hgi/gitlab-ci-git-push
  script:
    - gitlab/commit-tfstate.sh "ci-tfstate-$(cat version.txt)" "Changes to terraform.tfstate made by terraform [ci skip]" "terraform/production/terraform.tfstate"
  dependencies:
    - terraform-apply-production
    - version
  when: always
  
github-sync:
  stage: sync
  tags:
    - docker
  image: mercury/gitlab-ci-git-push
  script:
    - git checkout origin/master && subrepos/gitlab-ci-git-push/git-push ${GITHUB_REPO} ${CI_BUILD_REF_NAME}
  dependencies: []