# This script excepts the following Secret Variables to be defined in
# Gitlab project settings:
#  ANSIBLE_VAULT_PASSWORD
#  SSH_PRIVATE_KEY (e.g. "-----BEGIN RSA PRIVATE KEY-----
#                         ...
#                         -----END RSA PRIVATE KEY-----)"
#  GAMMA_OS_AUTH_URL
#  GAMMA_OS_USERNAME
#  GAMMA_OS_PASSWORD
#  DELTA_OS_AUTH_URL
#  DELTA_OS_USERNAME
#  DELTA_OS_PASSWORD
#  EMEDLAB_OS_AUTH_URL
#  EMEDLAB_OS_USERNAME
#  EMEDLAB_OS_PASSWORD
#  EMEDLAB_HTTP_PROXY
#  S3_ACCESS_KEY
#  S3_HOST
#  S3_SECRET_KEY
#  S3_IMAGE_BUCKET
#  TERRAFORM_CONSUL_TOKEN
variables:
  GITHUB_REPO: "git@github.com:wtsi-hgi/hgi-systems.git"
  GITLAB_REPO: "git@gitlab.internal.sanger.ac.uk:hgi/hgi-systems.git"
  TF_LOG: "" # anything other than "" to trace

# In general, additional variables should *not* be defined above unless they are 
# required to process .gitlab-ci.yml itself (i.e. they are used in this file outside 
# of the job scripts). 
# 
# To set or override a variable, create or edit a script in the before_scripts.d directory at 
# either the repo level or in the hgi image creation subrepo. The contents of those 
# two directories will be combined and the scripts sourced in "version" order (sort -V).
before_script: 
  - 'source "ci/source-before-scripts.sh" "ci/before_scripts.d"'

stages:
  - validate
  - terraform
  - ansible
  - sync

validate_s3:
  stage: validate
  tags:
   - docker
  image: quay.io/wtsi-hgi/taos
  script:
    - "ci/validate-s3.sh"
  only:
    - master

.production-gamma-hgi: &production-gamma-hgi-def
  variables:
    ENV: "production"
    REGION: "gamma-hgi"
  only:
    - master
    - production-gamma-hgi
  
.staging-gamma-hgi: &staging-gamma-hgi-def
  variables:
    ENV: "staging"
    REGION: "gamma-hgi"
  only:
    - develop
    - staging-gamma-hgi
  
.production-gamma-hgiarvados: &production-gamma-hgiarvados-def
  variables:
    ENV: "production"
    REGION: "gamma-hgiarvados"
  only:
    - master
    - production-gamma-hgiarvados
  
.staging-gamma-hgiarvados: &staging-gamma-hgiarvados-def
  variables:
    ENV: "staging"
    REGION: "gamma-hgiarvados"
  only:
    - develop
    - staging-gamma-hgiarvados
  
.production-delta-hgi: &production-delta-hgi-def
  variables:
    ENV: "production"
    REGION: "delta-hgi"
  only:
    - master
    - production-delta-hgi
  
.staging-delta-hgi: &staging-delta-hgi-def
  variables:
    ENV: "staging"
    REGION: "delta-hgi"
  only:
    - develop
    - staging-delta-hgi
  
.production-delta-hgiarvados: &production-delta-hgiarvados-def
  variables:
    ENV: "production"
    REGION: "delta-hgiarvados"
  only:
    - master
    - production-delta-hgiarvados
  
.staging-delta-hgiarvados: &staging-delta-hgiarvados-def
  variables:
    ENV: "staging"
    REGION: "delta-hgiarvados"
  only:
    - develop
    - staging-delta-hgiarvados
  
# .production-emedlab-arvados: &production-emedlab-arvados-def
#   variables:
#     ENV: "production"
#     REGION: "emedlab-arvados"
#   only:
#     - master
#     - production-emedlab-arvados
  
# .staging-emedlab-arvados: &staging-emedlab-arvados-def
#   variables:
#     ENV: "staging"
#     REGION: "emedlab-arvados"
#   only:
#     - develop
#     - staging-emedlab-arvados
  
.Openstack-vars-validate: &openstack-vars-validate-def
  stage: validate
  tags:
    - docker
  image: quay.io/wtsi-hgi/gitlab-ci-git-push
  script:
    - 'test -n "${OS_AUTH_URL}" || (echo "OS_AUTH_URL must be set!"; exit 1)'
    - 'test -n "${OS_USERNAME}" || test -n "${OS_USERID}" || (echo "OS_USERNAME or OS_USERID must be set!"; exit 1)'
    - 'test -n "${OS_PASSWORD}" || (echo "OS_PASSWORD must be set!"; exit 1)'
    - '((echo "${OS_AUTH_URL}" | grep -q "v3") && (test -n "${OS_DOMAIN_NAME}" || test -n "${OS_DOMAIN_ID}" || echo "WARNING: OS_DOMAIN_ID or OS_DOMAIN_NAME not set")) || exit 0'
  dependencies: []

.terraform-validate: &terraform-validate-def
  stage: validate
  tags:
    - docker
  image: quay.io/wtsi-hgi/taos
  script:
    - ci/terraform-validate.sh
  dependencies: []

openstack-vars-validate-production-gamma-hgi:
  <<: *openstack-vars-validate-def
  <<: *production-gamma-hgi-def
    
openstack-vars-validate-staging-gamma-hgi:
  <<: *openstack-vars-validate-def
  <<: *staging-gamma-hgi-def
    
openstack-vars-validate-production-gamma-hgiarvados:
  <<: *openstack-vars-validate-def
  <<: *production-gamma-hgiarvados-def
    
openstack-vars-validate-staging-gamma-hgiarvados:
  <<: *openstack-vars-validate-def
  <<: *staging-gamma-hgiarvados-def
    
openstack-vars-validate-production-delta-hgi:
  <<: *openstack-vars-validate-def
  <<: *production-delta-hgi-def
    
openstack-vars-validate-staging-delta-hgi:
  <<: *openstack-vars-validate-def
  <<: *staging-delta-hgi-def
    
openstack-vars-validate-production-delta-hgiarvados:
  <<: *openstack-vars-validate-def
  <<: *production-delta-hgiarvados-def
    
openstack-vars-validate-staging-delta-hgiarvados:
  <<: *openstack-vars-validate-def
  <<: *staging-delta-hgiarvados-def
    
# openstack-vars-validate-production-emedlab-arvados:
#   <<: *openstack-vars-validate-def
#   <<: *production-emedlab-arvados-def
    
# openstack-vars-validate-staging-emedlab-arvados:
#   <<: *openstack-vars-validate-def
#   <<: *staging-emedlab-arvados-def
    
terraform-validate-production-gamma-hgi:
  <<: *terraform-validate-def
  <<: *production-gamma-hgi-def
    
terraform-validate-staging-gamma-hgi:
  <<: *terraform-validate-def
  <<: *staging-gamma-hgi-def
    
terraform-validate-production-gamma-hgiarvados:
  <<: *terraform-validate-def
  <<: *production-gamma-hgiarvados-def
    
terraform-validate-staging-gamma-hgiarvados:
  <<: *terraform-validate-def
  <<: *staging-gamma-hgiarvados-def
    
terraform-validate-production-delta-hgi:
  <<: *terraform-validate-def
  <<: *production-delta-hgi-def
    
terraform-validate-staging-delta-hgi:
  <<: *terraform-validate-def
  <<: *staging-delta-hgi-def
    
terraform-validate-production-delta-hgiarvados:
  <<: *terraform-validate-def
  <<: *production-delta-hgiarvados-def
    
terraform-validate-staging-delta-hgiarvados:
  <<: *terraform-validate-def
  <<: *staging-delta-hgiarvados-def
    
# terraform-validate-production-emedlab-arvados:
#   <<: *terraform-validate-def
#   <<: *production-emedlab-arvados-def
    
# terraform-validate-staging-emedlab-arvados:
#   <<: *terraform-validate-def
#   <<: *staging-emedlab-arvados-def
    
.terraform: &terraform-def
  stage: terraform
  tags:
    - docker
  image: quay.io/wtsi-hgi/taos
  script:
    - ci/terraform.sh
  artifacts:
    paths:
      - artifacts
    when: always

terraform-production-gamma-hgi:
  <<: *terraform-def
  <<: *production-gamma-hgi-def

terraform-staging-gamma-hgi:
  <<: *terraform-def
  <<: *staging-gamma-hgi-def

terraform-production-gamma-hgiarvados:
  <<: *terraform-def
  <<: *production-gamma-hgiarvados-def

terraform-staging-gamma-hgiarvados:
  <<: *terraform-def
  <<: *staging-gamma-hgiarvados-def

terraform-production-delta-hgi:
  <<: *terraform-def
  <<: *production-delta-hgi-def

terraform-staging-delta-hgi:
  <<: *terraform-def
  <<: *staging-delta-hgi-def

terraform-production-delta-hgiarvados:
  <<: *terraform-def
  <<: *production-delta-hgiarvados-def

terraform-staging-delta-hgiarvados:
  <<: *terraform-def
  <<: *staging-delta-hgiarvados-def

# terraform-production-emedlab-arvados:
#   <<: *terraform-def
#   <<: *production-emedlab-arvados-def

# terraform-staging-emedlab-arvados:
#   <<: *terraform-def
#   <<: *staging-emedlab-arvados-def

.ansible: &ansible-def
  stage: ansible
  tags:
    - docker
  image: quay.io/wtsi-hgi/taos
  script:
    - ci/ansible.sh
  artifacts:
    paths:
      - artifacts
    when: always

ansible-production-gamma-hgi:
  <<: *ansible-def
  <<: *production-gamma-hgi-def

ansible-staging-gamma-hgi:
  <<: *ansible-def
  <<: *staging-gamma-hgi-def

ansible-production-gamma-hgiarvados:
  <<: *ansible-def
  <<: *production-gamma-hgiarvados-def

ansible-staging-gamma-hgiarvados:
  <<: *ansible-def
  <<: *staging-gamma-hgiarvados-def

ansible-production-delta-hgi:
  <<: *ansible-def
  <<: *production-delta-hgi-def

ansible-staging-delta-hgi:
  <<: *ansible-def
  <<: *staging-delta-hgi-def

ansible-production-delta-hgiarvados:
  <<: *ansible-def
  <<: *production-delta-hgiarvados-def

ansible-staging-delta-hgiarvados:
  <<: *ansible-def
  <<: *staging-delta-hgiarvados-def

# ansible-production-emedlab-arvados:
#   <<: *ansible-def
#   <<: *production-emedlab-arvados-def

# ansible-staging-emedlab-arvados:
#   <<: *ansible-def
#   <<: *staging-emedlab-arvados-def

github-sync:
  stage: sync
  tags:
    - docker
  image: quay.io/wtsi-hgi/gitlab-ci-git-push
  script:
    - git checkout origin/master && subrepos/gitlab-ci-git-push/git-push ${GITHUB_REPO} ${CI_BUILD_REF_NAME}
  dependencies: []
