# Copyright (c) 2016 Genome Research Ltd.
#
# Author: Christopher Harrison <ch12@sanger.ac.uk>
#
# This file is part of hgi-ansible.
#
# hgi-ansible is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 3 of the License, or (at your
# option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
---
# file: cookie-monsters.yml
- hosts: cookie-monsters
  tasks:
  # NOTE Do we need this? Can install from packages...
  # - name: Install iRODS dependencies
  #   apt: name={{item}} state=installed
  #   with_items:
  #     - wget
  #     - git
  #     - gcc
  #     - g++
  #     - perl
  #     - cpanminus
  #     - make
  #     - autoconf
  #     - automake
  #     - libtool
  #     - pkg-config
  #     - patch
  #     - ca-certificates
  #     - libboost-dev
  #     - libssl-dev
  #     - jq
  #     - perl-doc

  - name: Add Deadsnakes Python Repository
    apt_repository: repo='ppa:fkrull/deadsnakes' state=present
    register: deadsnakes_ppa

  - name: Install Python 3.5
    apt: pkg=python3.5 state=present update_cache=yes
    when: deadsnakes_ppa|success
    register: python_installed

# TODO
# Install iRODS 4.1.9 -- Do we need this? Can install from packages
# Set up iRODS
# Install baton dependencies?
# Install baton
# Install HGI Cookie Monster
# Create virtualenv?
# Set up Cookie Monster
# Install nginx
# Set up nginx reverse proxy for Cookie Monster
# TLS stuff
# Run Cookie Monster (n.b., dependency on cookie jars)
