# Copyright (c) 2016 Genome Research Ltd.
#
# Author: Christopher Harrison <ch12@sanger.ac.uk>
#
# This file is part of hgi-ansible.
#
# hgi-ansible is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 3 of the License, or (at your
# option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
---
# file: irodsians.yml
- hosts: irodsians
  tasks:
  - name: Install iCommands
    # FIXME This hardcodes Trusty as the target
    apt: deb='ftp://ftp.renci.org/pub/irods/releases/4.1.9/ubuntu14/irods-icommands-4.1.9-ubuntu14-x86_64.deb'
    environment:
      ftp_proxy: http://wwwcache.sanger.ac.uk:3128
    when: ansible_distribution == 'Ubuntu' and
          ansible_distribution_release == 'trusty'
    register: icommands

  - name: Install iRODS runtime libraries
    # FIXME This hardcodes Trusty as the target
    apt: deb='ftp://ftp.renci.org/pub/irods/releases/4.1.9/ubuntu14/irods-runtime-4.1.9-ubuntu14-x86_64.deb'
    environment:
      ftp_proxy: http://wwwcache.sanger.ac.uk:3128
    when: icommands|success
    register: irods_runtime

  - name: Install iRODS development tools
    # TODO Is this even necessary?
    # FIXME This hardcodes Trusty as the target
    apt: deb='ftp://ftp.renci.org/pub/irods/releases/4.1.9/ubuntu14/irods-dev-4.1.9-ubuntu14-x86_64.deb'
    environment:
      ftp_proxy: http://wwwcache.sanger.ac.uk:3128
    when: irods_runtime|success
