---

- name: install apt prerequisites
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: "{{ hail_apt_cache_valid_time }}"
  with_items:
    - g++
    - cmake
    - make
    - build-essential

- name: install conda prerequisites
  become: yes
  conda:
    name: seaborn
    version: "{{ hail_seaborn_version }}"
    executable: "{{ hail_anaconda_installation_location }}/bin/conda"

- name: check if Hail download is required
  stat:
    path: "{{ hail_jupyter_binary }}"
  changed_when: false
  register: jhail_binary

- block:
    - name: checkout Hail from GitHub
      git:
        repo: "{{ hail_repository }}"
        dest: "{{ hail_temp_directory }}"
        version: "{{ hail_version }}"

    - name: compile Hail
      command: "./gradlew -Dspark.version={{ hail_spark_version }} shadowJar archiveZip"
      args:
        chdir: "{{ hail_temp_directory }}"

    # Note: Currently (Ansible 2.3) `copy`'s `remote_src` does not support recursive copying
    - name: install Hail
      become: yes
      command: "mv {{ hail_temp_directory }} {{ hail_installation_location }}"
      notify: restart hail

  when: not jhail_binary.stat.exists
  always:
    - name: remove temp directory
      file:
        path: "{{ hail_temp_directory }}"
        state: absent

- name: set installation permissions
  become: yes
  file:
    path: "{{ hail_installation_location }}"
    owner: "{{ hail_user }}"
    recurse: yes
  notify: restart hail

- name: create link to jars directory expected by Hail
  become: yes
  file:
    src: "{{ hail_installation_location }}/build/libs"
    dest: "{{ hail_installation_location }}/jars"
    state: link

- name: create data directory for Jupyter user
  become: yes
  file:
    path: "{{ hail_data_directory }}"
    state: directory
    mode: 0700
    owner: "{{ hail_user }}"
    group: "{{ hail_user }}"

- name: provide link to Hail tutorials
  become: yes
  file:
    src: "{{ hail_installation_location }}/python/hail/docs/tutorials/"
    dest: "{{ hail_data_directory }}/tutorials"
    state: link

- name: set configuration for Jupyter
  become: yes
  template:
    src: jupyter_notebook_config.py.j2
    dest: "{{ hail_jupyter_configuration_location }}"
    owner: "{{ hail_user }}"
    mode: "0600"
  notify: restart hail
