---

- name: check if Hail download is required
  stat:
    path: "{{ hail_jupiter_binary }}"
  register: jhail_binary

- include: install.yml
  when: not jhail_binary.stat.exists

- include: startup.yml
