---

- name: install apt prerequisites
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: "{{ hail_apt_cache_valid_time }}"
  with_items:
    - nginx

- name: create data directory for Jupyter user
  become: yes
  file:
    path: "{{ hail_master_data_directory }}"
    state: directory
    mode: 0700
    owner: "{{ hail_common_user }}"
    group: "{{ hail_common_user }}"

- name: provide link to Hail tutorials
  become: yes
  file:
    src: "{{ hail_master_installation_location }}/python/hail/docs/tutorials/"
    dest: "{{ hail_master_data_directory }}/tutorials"
    state: link

- name: set configuration for Jupyter
  become: yes
  template:
    src: jupyter_notebook_config.py.j2
    dest: "{{ hail_master_jupyter_configuration_location }}"
    owner: "{{ hail_common_user }}"
    mode: 0600
  notify: restart hail

- name: setup systemd entry to control Hail
  become: yes
  template:
    src: hail.service.j2
    dest: "{{ hail_master_systemd_service_directory }}/hail.service"
  notify: restart hail
  register: hail_service

- name: reload systemd
  become: yes
  command: systemctl daemon-reload
  when: hail_service.changed

- name: setup s3 to backup hail data 
  import_role:
    name: s3-backup
  vars:
    s3_backup_source: "{{ consul_data_dir }}"
#    s3_backup_destination: "s3://{{ consul_server_s3_host }}/{{ consul_server_s3_backup_bucket }}/{{ hostvars[volume]['cloud_resource_name'] }}"
    s3_backup_destination: "s3://{{ consul_server_s3_host }}/{{ consul_server_s3_backup_bucket }}/{{ volume }}"
    s3_backup_s3_host: "{{ consul_server_s3_host }}"
    s3_backup_s3_access_key: "{{ consul_server_s3_access_key }}"
    s3_backup_s3_secret_key: "{{ consul_server_s3_secret_key }}"
    s3_backup_s3_bucket: "{{ consul_server_s3_backup_bucket }}"

