---

- include: tumf.systemd-service
  vars:
    systemd_service_name: hail
    systemd_service_Unit_Description: Hail Manager
    systemd_service_Service_ExecStart: "su - {{ hail_user }} {{ hail_jupyter_binary }}"
