---

- include_role:
    name: wtsi-hgi.ansible-role-systemd-service
  become: yes
  vars:
    systemd_service_name: hail
    systemd_service_Unit_Description: Hail Manager
    systemd_service_Service_ExecStart: "{{ hail_jupyter_binary }} --config={{ hail_jupyter_configuration_location }}"
    systemd_service_Service_User: "{{ hail_user }}"
    systemd_service_envs:
      - "PATH=$PATH:{{ hail_anaconda_installation_location }}/bin"
      - "SPARK_HOME={{ hail_spark_home }}/bin"
      - "HAIL_HOME={{ hail_installation_location }}"
      - "PYTHONPATH=$PYTHONPATH:$HAIL_HOME/python:$SPARK_HOME/python:$SPARK_HOME/python/lib/py4j-0.10.4-src.zip"
      - "SPARK_CLASSPATH=$HAIL_HOME/build/libs/hail-all-spark.jar"
