---

- name: setup systemd entry to control Hail
  become: yes
  template:
    src: hail.service.j2
    dest: "{{ hail_systemd_service_directory }}/hail.service"
  notify: restart hail
  register: hail_service

- name: reload systemd
  become: yes
  command: systemctl daemon-reload
  when: hail_service.changed
