---

_logrotate_GROUP_common_options:
  - daily
  - copytruncate
  - maxsize 1G
  - missingok
  - compress
  - rotate 1

logrotate_GROUP_scripts:
  - name: syslog
    path: /var/log/syslog
    options: "{{ _logrotate_GROUP_common_options }}"
  - name: kern.log
    path: /var/log/kern.log
    options: "{{ _logrotate_GROUP_common_options }}"

logrotate_GROUP_replace_old_configurations: true
