- name: restart nginx
  become: yes
  service:
    name: nginx
    state: restarted

- name: reconfigure arvados-sso-server
  become: yes
  command: dpkg-reconfigure arvados-sso-server

- name: generate sso app secret
  become: yes
  become_user: www-data
  command: bundle exec rails runner "{{ arvados_sso_generate_app_secret_script }}"
  args:
    chdir: /var/www/arvados-sso/current
  environment:
    HOME: /var/www
    RAILS_ENV: production

