arvados_cluster_group_name: "arvados-cluster-{{ arvados_cluster_id }}"
arvados_cluster_sso_app_id: arvados-server

arvados_cluster_db_user_sso: arvados_sso
arvados_cluster_db_name_sso: arvados_sso_production

arvados_cluster_db_user_api: arvados
arvados_cluster_db_name_api: arvados_api_production

arvados_cluster_max_body_size_m: 128

# Lists of Arvados server hostvars, names, and hosts (FQDNs)
arvados_cluster_masters: "{{ groups['arvados-masters'] | intersect(groups[arvados_cluster_group_name]) | default([]) | sort | map('extract', hostvars) | list() }}"
arvados_cluster_master_names: "{{ arvados_cluster_masters | map(attribute='cloud_resource_name') | list }}"
arvados_cluster_master_hosts: "{{ arvados_cluster_masters | map(attribute='cloud_resource_fqdn') | list }}"

arvados_cluster_keeps: "{{ groups['arvados-keeps'] | intersect(groups[arvados_cluster_group_name]) | default([]) | sort | map('extract', hostvars) | list() }}"
arvados_cluster_keep_hosts: "{{ arvados_cluster_keeps | map(attribute='cloud_resource_name') | list }}"
arvados_cluster_keep_hosts: "{{ arvados_cluster_keeps | map(attribute='cloud_resource_fqdn') | list }}"

arvados_cluster_keepproxys: "{{ groups['arvados-keepproxys'] | intersect(groups[arvados_cluster_group_name]) | default([]) | sort | map('extract', hostvars) | list() }}"
arvados_cluster_keepproxy_hosts: "{{ arvados_cluster_keepproxys | map(attribute='cloud_resource_name') | list }}"
arvados_cluster_keepproxy_hosts: "{{ arvados_cluster_keepproxys | map(attribute='cloud_resource_fqdn') | list }}"

arvados_cluster_ssos: "{{ groups['arvados-ssos'] | intersect(groups[arvados_cluster_group_name]) | default([]) | sort | map('extract', hostvars) | list() }}"
arvados_cluster_sso_hosts: "{{ arvados_cluster_ssos | map(attribute='cloud_resource_name') | list }}"
arvados_cluster_sso_hosts: "{{ arvados_cluster_ssos | map(attribute='cloud_resource_fqdn') | list }}"

arvados_cluster_workbenchs: "{{ groups['arvados-workbenchs'] | intersect(groups[arvados_cluster_group_name]) | default([]) | sort | map('extract', hostvars) | list() }}"
arvados_cluster_workbench_hosts: "{{ arvados_cluster_workbenchs | map(attribute='cloud_resource_name') | list }}"
arvados_cluster_workbench_hosts: "{{ arvados_cluster_workbenchs | map(attribute='cloud_resource_fqdn') | list }}"

arvados_cluster_compute_nodes: "{{ groups['arvados-compute_nodes'] | intersect(groups[arvados_cluster_group_name]) | default([]) | sort | map('extract', hostvars) | list() }}"
arvados_cluster_compute_node_hosts: "{{ arvados_cluster_compute_nodes | map(attribute='cloud_resource_name') | list }}"
arvados_cluster_compute_node_hosts: "{{ arvados_cluster_compute_nodes | map(attribute='cloud_resource_fqdn') | list }}"

# Public FQDNs of Arvados services
arvados_cluster_sso_host: "arvados-sso-{{ arvados_cluster_id }}.{{ arvados_cluster_domain }}"
arvados_cluster_api_host: "arvados-api-{{ arvados_cluster_id }}.{{ arvados_cluster_domain }}"
arvados_cluster_ws_host: "arvados-ws-{{ arvados_cluster_id }}.{{ arvados_cluster_domain }}"
arvados_cluster_git_host: "arvados-git-{{ arvados_cluster_id }}.{{ arvados_cluster_domain }"}
arvados_cluster_workbench_host: "arvados-workbench-{{ arvados_cluster_id }}.{{ arvados_cluster_domain }}"
arvados_cluster_keepproxy_host: "arvados-keep-{{ arvados_cluster_id }}.{{ arvados_cluster_domain }}"
arvados_cluster_download_host: "arvados-download-{{ arvados_cluster_id }}.{{ arvados_cluster_domain }}"
arvados_cluster_collections_host: "arvados-collections-{{ arvados_cluster_id }}.{{ arvados_cluster_domain }}"

