---


consul_cluster_GROUP_acl_management_name: mercury
consul_cluster_GROUP_acl_management_token: "{{ consul_credentials_GROUP_creds['acl-management'].token }}"

consul_cluster_GROUP_acl_terraform_name: mercury_terraform
consul_cluster_GROUP_acl_terraform_token: "{{ consul_credentials_GROUP_creds['terraform'].token }}"

consul_cluster_GROUP_acl_agent_name: agent_token
consul_cluster_GROUP_acl_agent_token: "{{ consul_credentials_GROUP_creds['agent'].token }}"

consul_cluster_GROUP_infoblox_username: "{{ infoblox_credentials_username }}"
consul_cluster_GROUP_infoblox_password: "{{ infoblox_credentials_password }}"
consul_cluster_GROUP_infoblox_api_server: "{{ infoblox_credentials_api_server }}"
consul_cluster_GROUP_infoblox_api_version: "{{ infoblox_credentials_api_version }}"

consul_cluster_GROUP_servers: "{{ groups['consul-servers'] | intersect(groups[consul_cluster_GROUP_name]) | default([]) | sort | map('extract', hostvars) | list() }}"
consul_cluster_GROUP_server_ips: "{{ consul_cluster_GROUP_servers | map(attribute='cloud_resource_private_ip') | list }}"
consul_cluster_GROUP_server_wan_ips: "{{ consul_cluster_GROUP_servers | map(attribute='cloud_resource_public_ip') | list }}"

consul_cluster_GROUP_acl_agent_master_token: "{{ consul_credentials_GROUP_creds['agent-master'].token }}"
consul_cluster_GROUP_server_acl_token: "{{ consul_credentials_GROUP_creds['default'].token }}"
consul_cluster_GROUP_acl_master_token: "{{ consul_credentials_GROUP_creds['master'].token }}"
