# vault contains:
# consul_cluster_acl_management_token: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXX

---

consul_cluster_servers: "{{ groups['consul-servers'] | map('extract', hostvars) | selectattr('consul_cluster', 'equalto', inventory_hostname) | map(attribute='inventory_hostname') | list }}"

consul_cluster_acl_management_name: mercury

consul_cluster_acl_terraform_name: mercury_terraform
consul_cluster_acl_terraform_token: "{{ consul_credentials['terraform'].token }}"

consul_cluster_acl_agent_name: agent_token
consul_cluster_acl_agent_token: "{{ consul_credentials['agent'].token }}"

consul_cluster_infoblox_username: "{{ infoblox_credentials_username }}"
consul_cluster_infoblox_password: "{{ infoblox_credentials_password }}"
consul_cluster_infoblox_api_server: "{{ infoblox_credentials_api_server }}"
consul_cluster_infoblox_api_version: "{{ infoblox_credentials_api_version }}"

