# Copyright (c) 2018 Genome Research Ltd.
#
# Author: Joshua C. Randall <jcrandall@alum.mit.edu>
#
# This file is part of hgi-systems.
#
# hgi-systems is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#
---
# file: roles/establish_bastion_connections/tasks/main.yml

 - name: set establish_bastion_connections_ROLE_FACT_connect_string on all hosts
   set_fact:
     establish_bastion_connections_ROLE_FACT_connect_string: "{{ bastion_user }}@{{ bastion_host }}"
   when: bastion_user is defined and bastion_host is defined

 - name: contact all bastion hosts once at the beginning of an ansible invocation
   run_once: true
   block:
     - debug:
         verbosity: 1
         msg: "Establishing bastion connections to: {{ establish_bastion_connections_bastion_connect_strings | join(',') }}"

     - name: contact bastion hosts just to say hello (and establish ControlMaster connections)
       delegate_to: "{{ item | regex_replace('.*[@]') }}"
       vars:
         ansible_user: "{{ item | regex_replace('[@].*') }}"
       command: hostname
       with_items: "{{ establish_bastion_connections_bastion_connect_strings }}"
       when: "establish_bastion_connections_bastion_connect_strings | count > 0"

 - set_fact:
     establish_bastion_connections_ROLE_FACT_ran: yes
