# Copyright (c) 2017 Genome Research Ltd.
#
# Author: Joshua C. Randall <jcrandall@alum.mit.edu>
#
# This file is part of hgi-systems.
#
# hgi-systems is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#
---
# file: roles/arvados-cluster/tasks/main.yml

- name: create keep_service entries for keep hosts
  delegate_to: "{{ arvados_cluster_delegate }}"
  arvados_keep_service:
    api_host: "{{ arvados_cluster_api_host }}"
    api_token: "{{ arvados_cluster_superuser_api_token }}"
    service_host: "{{ item }}"
    service_type: blob
  with_items: "{{ arvados_cluster_keep_hosts }}"

- name: create virtual_machine entries for shell hosts
  delegate_to: "{{ arvados_cluster_delegate }}"
  arvados_virtual_machine:
    api_host: "{{ arvados_cluster_api_host }}"
    api_token: "{{ arvados_cluster_superuser_api_token }}"
    uuid: "{{ arvados_cluster_id }}-2x53u-{{ item | hash('md5') | truncate(15, True, '') }}"
    hostname: "{{ item }}"
  with_items: "{{ arvados_cluster_shell_hosts }}"

- name: create api_client_authorizations for arvados-login-sync
  delegate_to: "{{ arvados_cluster_delegate }}"
  arvados_api_client_authorization:
    api_host: "{{ arvados_cluster_api_host }}"
    api_token: "{{ arvados_cluster_superuser_api_token }}"
    uuid: "{{ arvados_cluster_id }}-gj3su-{{ item | hash('md5') | truncate(15, True, '') }}"
    scopes: 
      - "GET /arvados/v1/virtual_machines/{{ arvados_cluster_id }}-2x53u-{{ item | hash('md5') | truncate(15, True, '') }}/logins"
    client_token: "{{ arvados_cluster_root_key | pbkdf2_hmac('arvados-login-sync-{{ item }}', 32) | b36encode }}"
  with_items: "{{ arvados_cluster_shell_hosts }}"

- name: create arvados repository
  delegate_to: "{{ arvados_cluster_delegate }}"
  arvados_repository:
    api_host: "{{ arvados_cluster_api_host }}"
    api_token: "{{ arvados_cluster_superuser_api_token }}"
    uuid: "{{ arvados_cluster_id }}-s0uqq-{{ 'arvados_repo' | hash('md5') | truncate(15, True, '') }}"
    owner_uuid: "{{ arvados_cluster_id }}-tpzed-000000000000000"
    name: arvados

- name: make arvados repository readable by all users
  delegate_to: "{{ arvados_cluster_delegate }}"
  arvados_link:
    api_host: "{{ arvados_cluster_api_host }}"
    api_token: "{{ arvados_cluster_superuser_api_token }}"
    uuid: "{{ arvados_cluster_id }}-o0j2j-{{ 'arvados_repo' | hash('md5') | truncate(15, True, '') }}"
    head_uuid: "{{ arvados_cluster_id }}-s0uqq-{{ 'arvados_repo' | hash('md5') | truncate(15, True, '') }}"
    tail_uuid: "{{ arvados_cluster_id }}-j7d0g-fffffffffffffff"
    link_class: permission
    name: can_read

- name: create group to own docker images by default
  delegate_to: "{{ arvados_cluster_delegate }}"
  arvados_group:
    api_host: "{{ arvados_cluster_api_host }}"
    api_token: "{{ arvados_cluster_superuser_api_token }}"
    uuid: "{{ arvados_cluster_id }}-j7d0g-{{ 'arvados_docker_project' | hash('md5') | truncate(15, True, '') }}"
    owner_uuid: "{{ arvados_cluster_id }}-tpzed-000000000000000"
    name: "Arvados Standard Docker Images"

- name: make docker project readable by all users
  delegate_to: "{{ arvados_cluster_delegate }}"
  arvados_link:
    api_host: "{{ arvados_cluster_api_host }}"
    api_token: "{{ arvados_cluster_superuser_api_token }}"
    uuid: "{{ arvados_cluster_id }}-o0j2j-{{ 'arvados_docker_project_all_link' | hash('md5') | truncate(15, True, '') }}"
    head_uuid: "{{ arvados_cluster_id }}-j7d0g-{{ 'arvados_docker_project' | hash('md5') | truncate(15, True, '') }}"
    tail_uuid: "{{ arvados_cluster_id }}-j7d0g-fffffffffffffff"
    link_class: permission
    name: can_read

