# Copyright (c) 2017 Genome Research Ltd.
#
# Author: Joshua C. Randall <jcrandall@alum.mit.edu>
#
# This file is part of hgi-systems.
#
# hgi-systems is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#
---
# file: roles/common/tasks/root-post-image-building.yml

- name: read root password data
  become: yes
  command: "getent {{ 'shadow' if ansible_os_family == 'Debian' else 'passwd' }} root"
  changed_when: false
  register: raw_root_password_data

- name: debug root password data
  debug:
    msg: "raw_root_password_data: {{ raw_root_password_data }}; _common_current_salt: {{ _common_current_salt }}; _common_current_password_hash: {{ _common_current_password_hash }}; _common_root_password_with_current_salt_hash_data: {{ _common_root_password_with_current_salt_hash_data }}; _common_root_password_with_current_salt_hash: {{ _common_root_password_with_current_salt_hash }}; _common_root_password_changed: {{ _common_root_password_changed }}; "


- name: set root password
  become: yes
  user:
    name: root
    createhome: no
    password: "{{ common_root_password_hash }}"
    state: present

- name: install GRL CA cert
  become: yes
  copy:
    src: grl-cacert.pem
    dest: /usr/local/share/ca-certificates/grl-cacert.crt
  tags:
    - common
  notify: update ca certificates
  when: ansible_os_family == 'Debian'

- name: ensure CA cert dir exists (freebsd)
  become: yes
  file:
    path: /usr/local/etc/ssl/certs
    state: directory
  tags:
    - common
  when: ansible_os_family == 'FreeBSD'
  
- name: install GRL CA cert (freebsd)
  become: yes
  copy:
    src: grl-cacert.pem
    dest: /usr/local/etc/ssl/certs/grl-cacert.crt
  tags:
    - common
  when: ansible_os_family == 'FreeBSD'
  
- name: create hgi group
  tags: common
  become: yes
  group:
    name: hgi
    gid: 1313

- name: create mercury user account and set password for console login
  tags: common
  become: yes
  user: 
    name: mercury
    uid: 13912
    group: hgi
    shell: /bin/bash
    password: "{{ mercury_system_password_crypted }}"

- name: give mercury NOPASSWD sudo access
  tags: common
  become: yes
  template:
    src: mercury_sudoers.j2
    dest: /etc/sudoers.d/mercury-nopasswd
    validate: "visudo -cf %s"
    owner: root
    group: root
    mode: 0440
  when: ansible_os_family == 'Debian'

- name: give mercury NOPASSWD sudo access
  tags: common
  become: yes
  template:
    src: mercury_sudoers.j2
    dest: /usr/local/etc/sudoers.d/mercury-nopasswd
    validate: "visudo -cf %s"
    owner: root
    group: wheel
    mode: 0440
  when: ansible_os_family == 'FreeBSD'

- name: set authorized keys for mercury
  tags: common
  become: yes
  authorized_key:
    user: mercury
    manage_dir: yes
    state: present
    key: "{{ item }}"
  with_file:
    - public_keys/mercury-farm3

