# Copyright (c) 2018 Genome Research Ltd.
#
# Authors:
#   Joshua C. Randall <jcrandall@alum.mit.edu>
#
# This file is part of hgi-systems.
#
# hgi-systems is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#
---
# file: roles/consul-template/defaults/main.yml

###############################################################################
# Variables that have no defaults and must be set
###############################################################################
#
# consul_template_user:
#   the user who should run consul-template
#
# consul_template_consul_token_file:
#   the file from which to read the token consul-template should use to 
#   authenticate to consul
#
###############################################################################

###############################################################################
# Vars with defaults that can be overridden
###############################################################################
consul_template_version: 0.19.4
consul_template_linux_amd64_checksum: "md5:3bfd83801bf4b69ca0ec1a2779274655"
consul_template_pid_file: "/var/run/consul-template.pid"
