# Copyright (c) 2016 Genome Research Ltd.
#
# Author: Christopher Harrison <ch12@sanger.ac.uk>
#
# This file is part of hgi-ansible.
#
# hgi-ansible is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 3 of the License, or (at your
# option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
---
# file: roles/cookie-jar/tasks/main.yml
- name: Add CouchDB PPA
  apt_repository: repo='ppa:couchdb/stable' state=present
  become: true
  register: couchdb_ppa

- name: Install CouchDB
  apt: pkg=couchdb state=present update_cache=true
  become: true
  when: couchdb_ppa|succeeded
  register: couchdb

# TODO Copy CouchDB configuration
#      Setup CouchDB users
#      Start service
