# Vault contains:
#   hail_cluster_jupyter_token: xxx
#   hail_cluster_ssh_key: xxx

---
# file: group_vars/spark-cluster-ew7-members/vars.yml

hail_cluster_id: ew7
hail_cluster_spark_build: 2.2.0-bin-hadoop2.8.2-netlib-lgpl-bf481e67
hail_cluster_hadoop_version: 2.8.2
