# Vault contains:
# consul_encrypt: xxxx

---

consul_version: 0.8.4

consul_home: /opt/consul

consul_advertise_address: "{{ hostvars[inventory_hostname]['openstack_servers'][0].public_v4 }}"
consul_datacenter: "{{ tenant }}"

consul_use_systemd: true
consul_use_upstart: false

consul_retry_join: true

consul_client_address: 0.0.0.0
consul_client_address_bind: true

consul_data_mountpoint: /data/consul
consul_data_dir: "{{ consul_data_mountpoint }}/data"

#consul_servers: "{{ groups['consul-servers'] | map('extract', hostvars, 'ansible_default_ipv4') | map(attribute='address') | list }}"
consul_servers: "{{ groups['consul-servers'] | map('extract', hostvars, 'openstack_server') | map(attribute='public_v4') | list }}"

consul_dns_allow_stale: true
consul_dns_max_stale: 30s
consul_dns_node_ttl: 30s
consul_dns_only_passing: true
consul_recursors: "{{ sanger_network_dns_servers }}"
