# Vault contains:
# consul_encrypt: xxxx

---

consul_version: 0.8.4

consul_home: /opt/consul

consul_commoners_advertise_address: "{{ os_public_v4 | default(tf_access_ip_v4) | default(ansible_default_ipv4.address) }}"
consul_advertise_address: "{{ consul_commoners_advertise_address }}"

consul_use_systemd: true
consul_use_upstart: false

consul_retry_join: true

consul_client_address: 0.0.0.0
consul_client_address_bind: true

consul_data_mountpoint: /data/consul
consul_data_dir: "{{ consul_data_mountpoint }}/data"

consul_server_inventory_hostnames: "{{ groups['consul-servers'] | intersect(groups[consul_cluster_group_name]) | default([]) | sort }}"
consul_server_advertise_addresses: "{{ consul_server_inventory_hostnames | map('extract', hostvars) | list() | json_query('[*].consul_commoners_advertise_address') }}"
consul_servers: "{{ consul_server_advertise_addresses }}"

consul_dns_allow_stale: true
consul_dns_max_stale: 30s
consul_dns_node_ttl: 30s
consul_dns_only_passing: true
consul_recursors: "{{ sanger_network_dns_servers }}"

