- name: restart munge as it does not support reload
  become: yes
  service:
    name: munge
    state: restarted
  listen: "reload slurm"

- name: restart slurmctld as it does not support reload
  become: yes
  service:
    name: slurmctld
    state: restarted
  listen: "reload slurm"

