# Copyright (c) 2017 Genome Research Ltd.
#
# Author: Joshua C. Randall <jcrandall@alum.mit.edu>
#
# This file is part of hgi-systems.
#
# hgi-systems is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#
---
# file: roles/arvados-keep/tasks/main.yml

################################################################################
# arvados-keepstore
################################################################################
- name: install arvados-keepstore and it prerequisites 
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_time }}"
  with_items:
    - keepstore
    - runit

- name: create runit directory for arvados-keepstore
  become: yes
  file:
    path: /etc/sv/arvados-keepstore
    state: directory

- name: install runit service for arvados-keepstore
  become: yes
  template:
    src: "arvados-keepstore.run.j2"
    dest: "/etc/sv/arvados-keepstore/run"
    mode: 0755
  notify:
   - restart arvados-keepstore

- name: create runit log directory for arvados-keepstore
  become: yes
  file:
    path: /etc/sv/arvados-keepstore/log
    state: directory

- name: install runit log service for arvados-keepstore
  become: yes
  template:
    src: "arvados-keepstore.log.run.j2"
    dest: "/etc/sv/arvados-keepstore/log/run"
    mode: 0755
  notify:
   - restart arvados-keepstore

- name: copy blob signing key
  become: yes
  copy:
    content: "{{ arvados_keep_blob_signing_key }}"
    dest: "{{ arvados_keep_blob_signing_key_file }}"
    owner: root
    mode: 0600
  notify:
   - restart arvados-keepstore

- name: copy data manager token
  become: yes
  copy:
    content: "{{ arvados_cluster_data_manager_api_token }}"
    dest: "{{ arvados_keep_data_manager_token_file }}"
    owner: root
    mode: 0600
  notify:
   - restart arvados-keepstore

- name: copy s3 access key
  become: yes
  copy:
    content: "{{ arvados_keep_s3_access_key }}"
    dest: "{{ arvados_keep_s3_access_key_file }}"
    owner: root
    mode: 0600
  notify:
   - restart arvados-keepstore

- name: copy s3 secret key
  become: yes
  copy:
    content: "{{ arvados_keep_s3_secret_key }}"
    dest: "{{ arvados_keep_s3_secret_key_file }}"
    owner: root
    mode: 0600
  notify:
   - restart arvados-keepstore

- name: enable arvados-keepstore
  become: yes
  runit:
    name: arvados-keepstore
    enabled: yes
    state: started
    service_dir: /etc/service
    service_src: /etc/sv

