# Copyright (c) 2017 Genome Research Ltd.
#
# Author: Joshua C. Randall <jcrandall@alum.mit.edu>
#
# This file is part of hgi-systems.
#
# hgi-systems is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#
---
# file: roles/arvados-keep/tasks/main.yml

################################################################################
# arvados-keepstore
################################################################################
- name: install arvados-keepstore and it prerequisites 
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_time }}"
  with_items:
    - keepstore
    - runit

- name: override keepstore with custom fix version from wtsi-hgi
  become: yes
  block:
    - name: download go 1.9 binaries
      get_url:
        url: https://storage.googleapis.com/golang/go1.9.1.linux-amd64.tar.gz
        dest: /root/go1.9.1.linux-amd64.tar.gz
    - name: install go 1.9
      unarchive:
        src: /root/go1.9.1.linux-amd64.tar.gz
        dest: /usr/local
        remote_src: yes      
    - name: install git for go build
      become: yes
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
        cache_valid_time: "{{ apt_cache_valid_time }}"
      with_items:
        - git
    - name: create gopath dir
      file:
        path: /usr/local/gopath/src/curoverse
        state: directory
    - name: sync wtsi-hgi/arvados git repo
      git:
        repo: "https://github.com/wtsi-hgi/arvados.git"
        dest: "/usr/local/gopath/src/curoverse/arvados"
        version: "fix/keepstore-s3-radosgw-empty-object"
    - name: go get keepstore
      environment:
        GOPATH: /usr/local/gopath
      command: /usr/local/go/bin/go get
      args:
        chdir: /usr/local/gopath/src/curoverse/arvados/services/keepstore
    - name: go build keepstore
      environment:
        GOPATH: /usr/local/gopath
      command: /usr/local/go/bin/go build
      args:
        chdir: /usr/local/gopath/src/curoverse/arvados/services/keepstore
    - name: go install keepstore
      environment:
        GOPATH: /usr/local/gopath
      command: /usr/local/go/bin/go install
      args:
        chdir: /usr/local/gopath/src/curoverse/arvados/services/keepstore
    - name: install compiled keepstore to /usr/bin/keepstore
      copy: 
        src: /usr/local/gopath/bin/keepstore
        dest: /usr/bin/keepstore
        remote_src: yes

- name: create runit directory for arvados-keepstore
  become: yes
  file:
    path: /etc/sv/arvados-keepstore
    state: directory

- name: create arvados keep config YAML file
  become: yes
  template:
    src: "arvados-keep-config.yaml.j2"
    dest: "{{ arvados_keep_config_file }}"
    mode: 0755
  notify:
   - restart arvados-keepstore

- name: install runit service for arvados-keepstore
  become: yes
  template:
    src: "arvados-keepstore.run.j2"
    dest: "/etc/sv/arvados-keepstore/run"
    mode: 0755
  notify:
   - restart arvados-keepstore

- name: create runit log directory for arvados-keepstore
  become: yes
  file:
    path: /etc/sv/arvados-keepstore/log
    state: directory

- name: install runit log service for arvados-keepstore
  become: yes
  template:
    src: "arvados-keepstore.log.run.j2"
    dest: "/etc/sv/arvados-keepstore/log/run"
    mode: 0755
  notify:
   - restart arvados-keepstore

- name: copy blob signing key
  become: yes
  copy:
    content: "{{ arvados_keep_blob_signing_key }}"
    dest: "{{ arvados_keep_blob_signing_key_file }}"
    owner: root
    mode: 0600
  notify:
   - restart arvados-keepstore

- name: copy data manager token
  become: yes
  copy:
    content: "{{ arvados_cluster_data_manager_api_token }}"
    dest: "{{ arvados_keep_data_manager_token_file }}"
    owner: root
    mode: 0600
  notify:
   - restart arvados-keepstore

- name: copy s3 access key
  become: yes
  copy:
    content: "{{ arvados_keep_s3_access_key }}"
    dest: "{{ arvados_keep_s3_access_key_file }}"
    owner: root
    mode: 0600
  notify:
   - restart arvados-keepstore

- name: copy s3 secret key
  become: yes
  copy:
    content: "{{ arvados_keep_s3_secret_key }}"
    dest: "{{ arvados_keep_s3_secret_key_file }}"
    owner: root
    mode: 0600
  notify:
   - restart arvados-keepstore

- name: ensure arvados keep s3 bucket exists
  tags:
    - s3
  delegate_to: localhost
  aws_s3:
    rgw: true
    s3_url: "{{ arvados_keep_s3_endpoint }}"
    aws_access_key: "{{ arvados_keep_s3_access_key }}"
    aws_secret_key: "{{ arvados_keep_s3_secret_key }}"
    bucket: "{{ arvados_keep_s3_bucket }}"
    permission: private
    mode: create

- name: enable arvados-keepstore
  become: yes
  runit:
    name: arvados-keepstore
    enabled: yes
    state: started
    service_dir: /etc/service
    service_src: /etc/sv

