# Copyright (c) 2017 Genome Research Ltd.
#
# Author: Joshua C. Randall <jcrandall@alum.mit.edu>
#
# This file is part of hgi-systems.
#
# hgi-systems is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#
---
# file: roles/arvados-keep/tasks/main.yml

################################################################################
# arvados-keepstore
################################################################################
- name: install arvados-keepstore and it prerequisites 
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: "{{ arvados_keep_apt_cache_valid_time }}"
  with_items:
    - keepstore
    - runit

- name: create runit directory for arvados-keepstore
  become: yes
  file:
    path: /etc/sv/arvados-keepstore
    state: directory

- name: create arvados keep restart command
  become: yes
  template:
    src: "arvados_keep_restart_command.sh.j2"
    dest: "{{ arvados_keep_restart_command }}"
    mode: 0755
    
- name: ensure consul-template.d exists
  become: yes
  file:
    path: /etc/consul-template.d
    state: directory
    mode: 0700

- name: create consul-template templates and config for keep
  block:
    - template:
        src: "{{ item }}.hcl.j2"
        dest: "/etc/consul-template.d/20-{{ item }}.hcl"
        mode: 0644
      become: yes
      notify:
        - reload consul-template
      with_items:
        - arvados-keep-config
        - arvados-keep-blob-signing-key
        - arvados-keep-data-manager-api-token
        - arvados-keep-s3-access-key
        - arvados-keep-s3-secret-key
  rescue:
    - name: make sure all handlers run
      meta: flush_handlers

- name: install runit service for arvados-keepstore
  become: yes
  template:
    src: "arvados-keepstore.run.j2"
    dest: "/etc/sv/arvados-keepstore/run"
    mode: 0755
  notify:
   - restart arvados-keepstore

- name: create runit log directory for arvados-keepstore
  become: yes
  file:
    path: /etc/sv/arvados-keepstore/log
    state: directory

- name: install runit log service for arvados-keepstore
  become: yes
  template:
    src: "arvados-keepstore.log.run.j2"
    dest: "/etc/sv/arvados-keepstore/log/run"
    mode: 0755
  notify:
   - restart arvados-keepstore

- name: enable arvados-keepstore
  become: yes
  runit:
    name: arvados-keepstore
    enabled: yes
    state: started
    service_dir: /etc/service
    service_src: /etc/sv

# set sysctl params for keepstore
- name: tune sysctl parameters for keepstore
  become: yes
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  with_items:
    - name: fs.file-max
      value: 11934410
    - name: kernel.msgmnb
      value: 65536
    - name: kernel.msgmax
      value: 65536
    - name: net.core.netdev_max_backlog
      value: 250000
    - name: net.core.optmem_max
      value: 67108864
    - name: net.core.rmem_max
      value: 67108864
    - name: net.core.wmem_max
      value: 67108864
    - name: net.ipv4.ip_local_port_range
      value: 1024 65535
    - name: net.ipv4.tcp_congestion_control
      value: htcp
    - name: net.ipv4.tcp_dsack
      value: 0
    - name: net.ipv4.tcp_fin_timeout
      value: 5
    - name: net.ipv4.tcp_keepalive_intvl
      value: 15
    - name: net.ipv4.tcp_keepalive_probes
      value: 5
    - name: net.ipv4.tcp_max_syn_backlog
      value: 200000
    - name: net.ipv4.tcp_max_tw_buckets
      value: 4000000
    - name: net.ipv4.tcp_mem
      value: 67108864 67108864 67108864
    - name: net.ipv4.tcp_retries2
      value: 10
    - name: net.ipv4.tcp_rfc1337
      value: 1
    - name: net.ipv4.tcp_rmem
      value: 4096 16777216 67108864
    - name: net.ipv4.tcp_sack
      value: 0
    - name: net.ipv4.tcp_wmem
      value: 4096 16777216 67108864
    - name: net.ipv4.tcp_window_scaling
      value: 1
    - name: vm.min_free_kbytes
      value: 204800
    - name: vm.page-cluster
      value: 20
    - name: vm.swappiness
      value: 10
  loop_control:
    label: "{{ item.name }}"
