---

# Requires:
# hail_jupyter_token:

hail_apt_cache_valid_time: 3600

hail_version: 0.1
hail_repository: https://github.com/hail-is/hail.git
hail_seaborn_version: 0.8.0

hail_installation_location: "/usr/local/hail-{{ hail_version }}"
hail_jupyter_binary: "{{ hail_installation_location }}/scripts/jhail"
hail_jupyter_configuration_location: "/etc/opt/jupyter_notebook_config.py"

hail_user: spark

hail_spark_version: 2.1.1
hail_spark_home: "/usr/local/spark-{{ hail_spark_version }}"

hail_anaconda_version: 4.4.0
hail_anaconda_installation_location: "/usr/local/anaconda-{{ hail_anaconda_version }}"
