---

# Requires:
# hail_jupyter_token:

hail_apt_cache_valid_time: 3600

hail_version: 0.1
hail_repository: https://github.com/hail-is/hail.git
hail_seaborn_version: 0.8.0

hail_installation_location: "/usr/local/hail-{{ hail_version }}"
hail_jupyter_binary: "{{ hail_installation_location }}/scripts/jhail"
hail_jupyter_configuration_location: "/etc/opt/jupyter_notebook_config.py"

hail_user: spark

hail_spark_version: 2.1.1
hail_spark_home: "/usr/local/spark-{{ hail_spark_version }}"

hail_anaconda_version: 4.4.0
hail_anaconda_installation_location: "/usr/local/anaconda-{{ hail_anaconda_version }}"

hail_service_start: "{{ hail_jupyter_binary }} --config={{ hail_jupyter_configuration_location }}"
hail_service_user: "{{ hail_user }}"
hail_service_environment_variables:
  PATH: "{{ hail_default_path }}:{{ hail_anaconda_installation_location }}/bin:{{ hail_installation_location }}/bin"
  HAIL_HOME: "{{ hail_installation_location }}"
  SPARK_HOME: "{{ hail_spark_home }}"
  PYTHONPATH: "{{ hail_installation_location }}/python:{{ hail_spark_home }}/python:{{ hail_spark_home }}/python/lib/py4j-0.10.4-src.zip"
  SPARK_CLASSPATH: "{{ hail_installation_location }}/build/libs/hail-all-spark.jar"

hail_data_directory: /data
