---

- name: import aptly apt repository key
  become: yes
  apt_key:
    keyserver: pool.sks-keyservers.net
    id: ED75B5A4483DA07C

- name: add aptly debian repository
  become: yes
  apt_repository:
    repo: deb http://repo.aptly.info/ squeeze main
    update_cache: yes

- name: install apt requirements
  become: yes
  apt:
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: "{{ aptly_apt_cache_valid_time }}"
  with_items:
    - aptly

- name: create aptly configuration
  become: yes
  template:
    src: aptly.conf.j2
    dest: /etc/aptly.conf
  notify: restart_aptly_api

- name: configure aptly REST API systemd service
  become: yes
  template:
    src: "aptly-api.service.j2"
    dest: "/etc/systemd/system/{{ aptly_api_service_name }}.service"
  notify: restart_aptly_api

- name: start aptly REST api
  become: yes
  systemd:
    name: "{{ aptly_api_service_name }}"
    state: started
    daemon_reload: yes
