- name: restart nginx
  become: yes
  systemd:
    name: nginx
    state: restarted
    daemon_reload: yes
    
- name: restart haproxy
  become: yes
  systemd:
    name: haproxy
    state: restarted
    daemon_reload: yes
    
- name: restart netdata
  become: yes
  systemd:
    name: netdata
    state: restarted
    daemon_reload: yes
    
- name: restart arvados-ws
  become: yes
  systemd:
    name: arvados-ws
    state: restarted
    daemon_reload: yes

- name: restart arvados-git-httpd
  become: yes
  systemd:
    name: arvados-git-httpd
    state: restarted
    daemon_reload: yes

- name: restart arvados-git-httpd
  become: yes
  systemd:
    name: arvados-git-httpd
    state: restarted
    daemon_reload: yes

- name: restart crunch-dispatch-slurm
  become: yes
  systemd:
    name: crunch-dispatch-slurm
    state: restarted
    daemon_reload: yes

- name: restart runit
  become: yes
  systemd: 
    name: runit
    state: restarted
    daemon_reload: yes

- name: restart crunch-dispatch-pipelines
  become: yes
  runit:
    name: crunch-dispatch-pipelines
    enabled: yes
    state: restarted
    service_dir: /etc/service
    service_src: /etc/sv
  notify:
   - restart runit

- name: restart crunch-dispatch-jobs
  become: yes
  runit:
    name: crunch-dispatch-jobs
    enabled: yes
    state: restarted
    service_dir: /etc/service
    service_src: /etc/sv
  notify:
   - restart runit
