---

- name: create hail group
  become: yes
  group:
    name: "{{ hail_common_user }}"

- name: create hail user account
  become: yes
  user:
    name: "{{ hail_common_user }}"
    group: "{{ hail_common_user }}"
    shell: /bin/bash

- name: set authorized keys for hail
  become: yes
  authorized_key:
    user: "{{ hail_common_user }}"
    manage_dir: yes
    state: present
    key: "{{ item }}"
  with_file:
    - public_keys/hail

- name: install apt prerequisites
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: "{{ all_apt_cache_valid_time }}"
  with_items:
    - g++
    - cmake
    - make
    - build-essential
    - openjdk-8-jre-headless
    - openjdk-8-jdk
    - git-all
    - libopenblas-base
    - libatlas3-base
    - libnetlib-java
    - r-base

- include: conda-6096-patch.yml

- name: install conda prerequisites
  become: yes
  conda:
    name: seaborn
    version: "{{ hail_common_seaborn_version }}"
    executable: "{{ hail_common_anaconda_installation_location }}/bin/conda"

- name: check if Hail download is required
  stat:
    path: "{{ hail_common_check_installed }}"
  changed_when: false
  register: hail_installed

- block:
    - name: checkout Hail from GitHub
      git:
        repo: "{{ hail_common_repository }}"
        dest: "{{ hail_common_temp_directory }}"
        version: "{{ hail_common_version }}"

    - name: compile Hail
      command: "./gradlew -Dspark.version={{ hail_common_spark_version | regex_replace('([0-9.]+)-.*', '\\1') }} shadowJar archiveZip"
      args:
        chdir: "{{ hail_common_temp_directory }}"

    # Note: Currently (Ansible 2.3) `copy`'s `remote_src` does not support recursive copying
    - name: install Hail
      become: yes
      command: "mv {{ hail_common_temp_directory }} {{ hail_common_installation_location }}"
      notify: restart hail

  when: not hail_installed.stat.exists
  always:
    - name: remove temp directory
      file:
        path: "{{ hail_common_temp_directory }}"
        state: absent

- name: set installation permissions
  become: yes
  file:
    path: "{{ hail_common_installation_location }}"
    owner: "{{ hail_common_user }}"
    recurse: yes
  notify: restart hail

- name: create link to jars directory expected by Hail
  become: yes
  file:
    src: "{{ hail_common_installation_location }}/build/libs"
    dest: "{{ hail_common_installation_location }}/jars"
    state: link

