# Copyright (c) 2018 Genome Research Ltd.
#
# Author: Joshua C. Randall <jcrandall@alum.mit.edu>
#
# This file is part of hgi-systems.
#
# hgi-systems is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#
---
# file: roles/docker-consul-server/tasks/main.yml

- name: ensure data directory exists
  become: yes
  file:
    path: "{{ docker_consul_server_data_dir }}"
    state: directory
    mode: 700

- name: configure docker-consul-server systemd service
  become: yes
  template:
    src: "docker-consul-server.service.j2"
    dest: "/etc/systemd/system/docker-consul-server.service"
  notify: systemd restart docker-consul-server

- name: add bash alias to run consul in docker
  become: yes
  copy:
    content: "alias consul='docker run --net=host consul'"
    dest: /etc/profile.d/consul-alias.sh

- name: ensure server config directory exists
  become: yes
  file:
    path: "{{ docker_consul_server_config_dir }}"
    state: directory

- name: configure docker-consul-server (when not image-building)
  become: yes
  template:
    src: "00-docker-consul-server.json.j2"
    dest: "{{ docker_consul_server_config_dir }}/00-docker-consul-server.json"
  when: "not 'image-building' in group_names"
  notify: systemd restart docker-consul-server

- name: create ACL token required for the server to communicate fully with the rest of the cluster
  consul_acl:
    # Note: This HAS to be done on localhost as the host is not externally accessible accessible until this ACL is set
    host: localhost
    name: "server_token"
    token: "{{ docker_consul_server_acl_token }}"
    mgmt_token: "{{ docker_consul_server_acl_master_token }}"
    token_type: client
    rules:
      - agent: ""
        policy: write
      - node: ""
        policy: write
      - service: "consul"
        policy: write

