---

gitlab_image_builder_project_gitlab_url: "{{ gitlab_url }}"
gitlab_image_builder_project_gitlab_token: "{{ gitlab_token }}"
gitlab_image_builder_project_gitlab_group: "{{ gitlab_hgi_group }}"

gitlab_image_builder_project_committer_name: Ansible Synchroniser
gitlab_image_builder_project_committer_email: hgi@sanger.ac.uk

gitlab_image_builder_project_projects:
  - name: test-1
    settings:
      files: "{{ gitlab_image_builder_project_synchronisations.files | json_query('*') }}"
      templates:
        - "{{
            gitlab_image_builder_project_synchronisations.templates.ansible_groups
              | combine(dict(
                  variables=dict(
                      ansible_groups=['common']
                  )
                ))
          }}"
        - "{{
            gitlab_image_builder_project_synchronisations.templates.readme
              | combine(dict(
                  variables=dict(
                      repository_name='hgi-image-creation',
                      title='Builds Base Images for HGI',
                      description='Uses CI to build base images for HGI instances.'
                  )
                ))
          }}"
      subrepos: "{{ gitlab_image_builder_project_synchronisations.subrepos | json_query('*') }}"
