
- name: ensure we have openstack-zeta-hgi dynamic inventory
  when: managed_by is defined and managed_by == "ansible"
  assert:
    that: groups['canary-openstack-zeta-hgi'] is defined
    msg: "openstack-zeta-hgi dynamic inventory does not appear to have run (group 'canary-openstack-zeta-hgi' not present)"

- name: ensure we have openstack-zeta-hgi-ci dynamic inventory
  when: managed_by is defined and managed_by == "ansible"
  assert:
    that: groups['canary-openstack-zeta-hgi-ci'] is defined
    msg: "openstack-zeta-hgi-ci dynamic inventory does not appear to have run (group 'canary-openstack-zeta-hgi-ci' not present)"

