# Copyright (c) 2017, 2018 Genome Research Ltd.
#
# Author: Joshua C. Randall <jcrandall@alum.mit.edu>
#
# This file is part of hgi-systems.
#
# hgi-systems is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#
---
# file: roles/arvados-api-db/tasks/main.yml

################################################################################
# prepare directories
################################################################################
- name: create directories within arvados data dir
  become: yes
  file:
    path: "{{ arvados_api_db_data_dir }}/{{ item }}"
    state: directory
  with_items:
    - postgresql

- name: create etc-postgresql dir
  become: yes
  file:
    path: "{{ arvados_api_db_data_dir }}/etc-postgresql"
    state: directory

- name: link etc-postgresql dir to /etc/postgresql
  become: yes
  file:
    path: /etc/postgresql
    src: "{{ arvados_api_db_data_dir }}/etc-postgresql"
    state: link

################################################################################
# arvados-api-db
################################################################################
- name: install postgresql
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: "{{ all_apt_cache_valid_time }}"
  with_items:
    - "postgresql={{ arvados_api_db_postgresql_package_version }}"
    - python-psycopg2

- name: set ownership of postgres dirs
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    owner: postgres
    group: postgres
    recurse: yes
  with_items: 
    - "{{ arvados_api_db_data_dir }}/etc-postgresql"
    - "{{ arvados_api_db_data_dir }}/postgresql"

- name: delete default main postgresql cluster
  become: yes
  command: "pg_dropcluster --stop {{ arvados_api_db_postgresql_version }} main"
  args:
    removes: /etc/postgresql/{{ arvados_api_db_postgresql_version }}/main

- name: create postgresql cluster
  become: yes
  command: "pg_createcluster -u postgres -d {{ arvados_api_db_data_dir }}/postgresql/{{ arvados_api_db_postgresql_version }}/arvados_api -p 5432 --start {{ arvados_api_db_postgresql_version }} arvados_api"
  args:
    creates: /etc/postgresql/{{ arvados_api_db_postgresql_version }}/arvados_api
  register: arvados_api_db_REGISTER_configure_postgresql

- name: create postgres conf.d
  become: yes
  file:
    path: "/etc/postgresql/{{ arvados_api_db_postgresql_version }}/arvados_api/conf.d"
    state: directory
  notify:
    - restart postgresql

- name: add postgres conf.d include_dir to postgresql.conf
  become: yes
  lineinfile:
    path: "/etc/postgresql/{{ arvados_api_db_postgresql_version }}/arvados_api/postgresql.conf"
    state: present
    insertafter: EOF
    line: "include_dir '/etc/postgresql/{{ arvados_api_db_postgresql_version }}/arvados_api/conf.d'"
  notify:
    - restart postgresql

- name: configure pg_hba.conf to allow arvados user to connect remotely
  become: yes
  lineinfile:
    path: "/etc/postgresql/{{ arvados_api_db_postgresql_version }}/arvados_api/pg_hba.conf"
    state: present
    insertafter: EOF
    line: "host    all     arvados 10.0.0.0/8      md5"
  notify:
    - restart postgresql

- name: template out postgres conf.d files
  become: yes
  template: 
    src: "{{ item }}.conf.j2"
    dest: "/etc/postgresql/{{ arvados_api_db_postgresql_version }}/arvados_api/conf.d/{{ item }}.conf"
  notify:
    - restart postgresql
  with_items:
    - autovacuum
    - connections
    - resources
    - runtime_stats
    - query_tuning
    - write_ahead_log

- name: allow netdata user to connect to postgres locally for monitoring
  become: yes
  lineinfile:
    path: "/etc/postgresql/{{ arvados_api_db_postgresql_version }}/arvados_api/pg_hba.conf"
    state: present
    insertafter: "^local"
    line: "local   all             netdata                                 peer"
  notify:
    - restart postgresql

- name: ensure postgresql has restarted before creating user and db
  meta: flush_handlers

- name: create postgresql user for arvados api
  become: yes
  become_user: postgres
  postgresql_user:
    name: "{{ arvados_cluster_db_user_api }}"
    password: "{{ arvados_cluster_db_password_api }}"
    encrypted: yes
    role_attr_flags: "NOSUPERUSER,NOCREATEROLE"

- name: create arvados api database
  become: yes
  become_user: postgres
  postgresql_db:
    name: "{{ arvados_cluster_db_name_api }}"
    template: template0
    encoding: UTF8
    owner: "{{ arvados_cluster_db_user_api }}"

- name: enable postgresql systemd service
  become: yes
  systemd:
    name: "postgresql@{{ arvados_api_db_postgresql_version }}-arvados_api"
    enabled: yes
    daemon_reload: yes

- name: create postgresql superuser for netdata monitoring
  become: yes
  become_user: postgres
  postgresql_user:
    name: netdata
    role_attr_flags: SUPERUSER

# set sysctl params for postgres
- name: tune sysctl parameters for postgres
  become: yes
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  with_items:
    - name: fs.file-max
      value: 11934410
    - name: kernel.msgmnb
      value: 65536
    - name: kernel.msgmax
      value: 65536
    - name: net.core.netdev_max_backlog
      value: 250000
    - name: net.core.optmem_max
      value: 67108864
    - name: net.core.rmem_max
      value: 67108864
    - name: net.core.somaxconn
      value: "{{ arvados_master_sysctl_somaxconn }}"
    - name: net.core.wmem_max
      value: 67108864
    - name: net.ipv4.ip_local_port_range
      value: 1024 65535
    - name: net.ipv4.tcp_congestion_control
      value: htcp
    - name: net.ipv4.tcp_dsack
      value: 0
    - name: net.ipv4.tcp_fin_timeout
      value: 5
    - name: net.ipv4.tcp_keepalive_time
      value: 30
    - name: net.ipv4.tcp_keepalive_intvl
      value: 5
    - name: net.ipv4.tcp_keepalive_probes
      value: 6
    - name: net.ipv4.tcp_max_syn_backlog
      value: 200000
    - name: net.ipv4.tcp_max_tw_buckets
      value: 4000000
    - name: net.ipv4.tcp_mem
      value: 67108864 67108864 67108864
    - name: net.ipv4.tcp_retries2
      value: 10
    - name: net.ipv4.tcp_rfc1337
      value: 1
    - name: net.ipv4.tcp_rmem
      value: 4096 16777216 67108864
    - name: net.ipv4.tcp_sack
      value: 0
    - name: net.ipv4.tcp_wmem
      value: 4096 16777216 67108864
    - name: net.ipv4.tcp_window_scaling
      value: 1
    - name: net.nf_conntrack_max
      value: 1048576
    - name: vm.min_free_kbytes
      value: 204800
    - name: vm.page-cluster
      value: 20
    - name: vm.swappiness
      value: 10
  loop_control:
    label: "{{ item.name }}"

