---

# TODO: Align this with the gitlab-runners role

- name: create GitLab image builder projects
  delegate_to: "{{ gitlab_image_builder_project_delegate }}"
  gitlab_project:
    server_url: "{{ gitlab_image_builder_project_gitlab_url }}"
    login_token: "{{ gitlab_image_builder_project_gitlab_token }}"
    name: "{{ item }}"
    group: "{{ gitlab_image_builder_project_gitlab_group }}"
    public: True
    issues_enabled: True
    wiki_enabled: False
    snippets_enabled: True
    merge_requests_enabled: True
    state: present
  with_items: "{{ gitlab_image_builder_project_projects | json_query('[].name') }}"

- block:
    - name: create temporary working directory
      tempfile:
        state: directory
        suffix: build
      register: temp_directory
      changed_when: false

    - set_fact:
        common_repository: "{{ temp_directory.path }}/{{ gitlab_image_builder_project_common_repository_checkout_directory }}"
        gitlab_host: "{{ gitlab_image_builder_project_gitlab_url | regex_replace('^.*://(.*)', '\\1') }}"

    - name: checkout common image creation repository
      delegate_to: "{{ gitlab_image_builder_project_delegate }}"
      git:
        repo: "{{ gitlab_image_builder_project_common_repository_url }}"
        dest: "{{ common_repository }}"
        version: "{{ gitlab_image_builder_project_common_repository_branch }}"
      changed_when: false

    - name: synchronise GitHub image builder projects
      delegate_to: "{{ gitlab_image_builder_project_delegate }}"
      gitcommonsync:
        repository: "git@{{ gitlab_host }}:{{ gitlab_image_builder_project_gitlab_group }}/{{ item.name }}.git"
        committer_name: "{{ gitlab_image_builder_project_committer_name }}"
        committer_email: "{{ gitlab_image_builder_project_committer_email }}"
        files: "{{
          item.settings.files
            | manipulate_in_list(
                'src', replace='%s/%s/files/\\1'
                               % (common_repository, gitlab_image_builder_project_common_repository_directory))
            | list
        }}"
        templates: "{{
          item.settings.templates
            | manipulate_in_list(
                'src', replace='%s/%s/templates/\\1'
                               % (common_repository, gitlab_image_builder_project_common_repository_directory))
            | list
        }}"
        subrepos: "{{ item.settings.subrepos }}"
      # XXX: In Ansible 2.3.1.0, the module's shebang does not seem to be taken into account so setting specifically
      vars:
        ansible_python_interpreter: /usr/bin/env python3
      with_items: "{{ gitlab_image_builder_project_projects }}"

  always:
    - name: remove temp directory
      file:
        path: "{{ temp_directory.path }}"
        state: absent
      changed_when: false
      when: temp_directory is defined
