---

# Requires:
#   - hail_master_jupyter_token
#   - hail_master_version
#   - hail_master_spark_version

hail_master_apt_cache_valid_time: 3600

# XXX: it feels like we should be more DRY here
hail_master_spark_home: "/usr/local/spark-{{ hail_master_spark_version }}"
hail_master_version: 0.1
hail_master_installation_location: "/usr/local/hail-{{ hail_master_version }}"

hail_master_jupyter_binary: "{{ hail_master_installation_location }}/scripts/jhail"
hail_master_jupyter_configuration_location: "/etc/opt/jupyter_notebook_config.py"

hail_master_service_start: "{{ hail_master_jupyter_binary }} --config={{ hail_master_jupyter_configuration_location }}"
hail_master_service_user: "{{ hail_user }}"
hail_master_service_environment_variables:
  PATH: "{{ hail_master_default_path }}:{{ hail_master_anaconda_installation_location }}/bin:{{ hail_master_installation_location }}/bin"
  HAIL_MASTER_HOME: "{{ hail_master_installation_location }}"
  SPARK_HOME: "{{ hail_master_spark_home }}"
  PYTHONPATH: "{{ hail_master_installation_location }}/python:{{ hail_master_spark_home }}/python:{{ hail_master_spark_home }}/python/lib/py4j-0.10.4-src.zip"
  SPARK_CLASSPATH: "{{ hail_master_installation_location }}/build/libs/hail-all-spark.jar"

hail_master_data_directory: /data

hail_master_user: spark
