---

# Requires:
#   - hail_master_jupyter_token
#   - hail_master_version
#   - hail_master_spark_version

hail_master_apt_cache_valid_time: 3600

hail_master_jupyter_binary: "{{ hail_common_installation_location }}/scripts/jhail"
hail_master_jupyter_configuration_location: "/etc/opt/jupyter_notebook_config.py"

hail_master_service_start: "{{ hail_master_jupyter_binary }} --config={{ hail_master_jupyter_configuration_location }}"
hail_master_service_user: "{{ hail_common_user }}"
hail_master_service_environment_variables:
  PATH: "{{ hail_master_default_path }}:{{ hail_master_anaconda_installation_location }}/bin:{{ hail_common_installation_location }}/bin"
  HAIL_HOME: "{{ hail_common_installation_location }}"
  SPARK_HOME: "{{ hail_common_spark_home }}"
  PYTHONPATH: "{{ hail_common_installation_location }}/python:{{ hail_common_spark_home }}/python:{{ hail_common_spark_home }}/python/lib/py4j-0.10.4-src.zip"

#  SPARK_CLASSPATH: "{{ hail_common_installation_location }}/build/libs/hail-all-spark.jar"

hail_master_data_directory: /data


