- name: restart runit
  become: yes
  systemd: 
    name: runit
    state: restarted

- name: restart arvados-keepstore
  become: yes
  runit:
    name: arvados-keepstore
    enabled: yes
    state: restarted
    service_dir: /etc/service
    service_src: /etc/sv
  notify:
   - restart runit

