# Vault contains:
#   hail_cluster_jupyter_token: xxx
#   hail_cluster_ssh_key: xxx

---

hail_cluster_id: mercury
hail_cluster_spark_build: 2.1.2-bin-hadoop2.8.2-netlib-lgpl-5ec42a8c
hail_cluster_hadoop_version: 2.8.2
