- name: restart arvados-docker-cleaner
  become: yes
  runit:
    name: arvados-docker-cleaner
    state: restarted

- name: reboot host in 1m
  become: yes
  command: shutdown -r +1 "Ansible rebooting host"
  async: 0
  poll: 0
  ignore_errors: true
  when: "not 'image-building' in group_names"
  listen: reboot compute node

- name: wait for reboot to complete
  become: no
  delegate_to: "{{ bastion_host }}"
  wait_for:
    host: "{{ ansible_host }}"
    port: "{{ ansible_port }}"
    delay: 90
    timeout: 360
  when: "not 'image-building' in group_names"
  listen: reboot compute node
