# Copyright (c) 2017 Genome Research Ltd.
#
# Authors: 
#   Colin Nolan <colin.nolan@sanger.ac.uk>
#   Joshua C. Randall <jcrandall@alum.mit.edu>
#
# This file is part of hgi-systems.
#
# hgi-systems is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#
---
# file: roles/hgi-consul/defaults/main.yml

###############################################################################
# Variables that have no defaults and must be set
###############################################################################
#
# hgi_consul_server_host_list:
#   list of server hosts (inventory hostnames) for this cluster
#
# hgi_consul_agent_host_list:
#   list of agent hosts (inventory hostnames) for this cluster
#
# hgi_consul_advertise_address:
#   IP address to advertise within the datacentre
#
# hgi_consul_acl_token:
#   ACL token
#
# hgi_consul_acl_master_token:
#   ACL master token
#
# hgi_consul_acl_agent_master_token
#   ACL agent master token
#
# hgi_consul_s3_host:
#   S3 host to use for backups
#
# hgi_consul_s3_access_key:
#   S3 access key for backups
#
# hgi_consul_s3_secret_key:
#   S3 secret key for backups
#
###############################################################################

###############################################################################
# Vars that can be overridden
###############################################################################
hgi_consul_s3_backup_bucket: consul-backup
hgi_consul_advertise_address_wan: false
hgi_consul_advertise_addresses_wan: []
hgi_consul_service_manager: systemd
hgi_consul_data_dir: /var/consul/data
hgi_consul_s3_backup_source_dir: "{{ hgi_consul_data_dir }}"
hgi_consul_s3_backup_dest_path: "{{ inventory_hostname }}"
hgi_consul_volume_size_gb:
hgi_consul_recursors:
hgi_consul_servers:
hgi_consul_node_name:
hgi_consul_encrypt:
hgi_consul_datacenter: default
hgi_consul_retry_join_list: []

###############################################################################
# DNS settings
###############################################################################
hgi_consul_upstream_dns_servers: []

###############################################################################
# Node types
###############################################################################
hgi_consul_server_p: "{{ inventory_hostname in hgi_consul_server_host_list }}"
hgi_consul_agent_p: "{{ inventory_hostname in hgi_consul_agent_host_list }}"

###############################################################################
# General settings
###############################################################################
hgi_consul_apt_cache_valid_time: 86400
