---

- name: restart consul
  become: yes
  systemd:
    name: "{{ netdata_consul_service_name }}"
    state: restarted
  when: "not 'image-building' in group_names"

- name: restart consul-template
  become: yes
  systemd:
    name: consul-template
    state: restarted
