# Copyright (c) 2014 Genome Research Ltd.
#
# Author: Joshua C. Randall <jcrandall@alum.mit.edu>
#
# This file is part of hgi-ansible.
#
# hgi-ansible is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#
---
# file: roles/chronos/vars/main.yml

chronos_libmesos_so: "/software/hgi/pkglocal/mesos-0.20.0/lib/libmesos.so"
chronos_java_bin: "/usr/bin/java"
chronos_java_heap: "2048m"
chronos_java_cp: "/software/hgi/pkglocal/chronos-git-2.2.0-gdc36912/target/chronos-2.2.0_mesos-0.20.0-SNAPSHOT.jar"
chronos_java_main: "com.airbnb.scheduler.Main"
chronos_mesos_zk_uri: "zk://{% for host in groups['zookeepers'] %}{{ host }}:2181{% if not loop.last %},{% endif %}{% endfor %}/mesos"
chronos_zk_hosts: "{% for host in groups['zookeepers'] %}{{ host }}:2181{% if not loop.last %},{% endif %}{% endfor %}"
chronos_zk_path: "/chronos/state"
chronos_mesos_role: "chronos"
chronos_http_port: 50060
chronos_https_port: 50061
chronos_failover_timeout_s: 600
chronos_hostname: "{{ hostvars[inventory_hostname]['ansible_fqdn'] }}"
