# Copyright (c) 2017 Genome Research Ltd.
#
# Author: Joshua C. Randall <jcrandall@alum.mit.edu>
#
# This file is part of hgi-systems.
#
# hgi-systems is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#
---
# file: roles/netdata/tasks/main.yml

- name: install prerequisite packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: "{{ all_apt_cache_valid_time }}"
  with_items:
    - zlib1g-dev
    - uuid-dev
    - libmnl-dev
    - gcc
    - make
    - git
    - autoconf
    - autoconf-archive
    - autogen
    - automake
    - pkg-config
    - curl
    - bash
    - curl
    - iproute
    - python
    - python-yaml
    - python-mysqldb
    - python-psycopg2
    - python-pymongo
    - nodejs
    - lm-sensors
    - libmnl0
    - netcat

- name: fetch netdata source from git
  become: yes
  git:
    repo: https://github.com/firehol/netdata.git
    version: v1.8.0
    depth: 1
    dest: /usr/local/src/netdata
  register: netdata_git_source

- name: run netdata installer
  become: yes
  command: ./netdata-installer.sh --dont-wait
  args:
    chdir: /usr/local/src/netdata
  when: netdata_git_source.changed

- name: configure netdata consul service
  become: yes
  template:
    src: consul-netdata.json.j2
    dest: /etc/consul.d/consul-netdata.json
    owner: root
  notify:
    - reload consul
