---
  - name: validate setup variables
    assert:
      that:
        - github_to_gitlab_mattermost_webhook_url | mandatory
        - github_to_gitlab_gitlab_username | mandatory
        - github_to_gitlab_gitlab_password | mandatory
    no_log: True

  - name: install apt requirements
    become: yes
    apt:
      name: python-pip

  - name: install pip requirements
    become: yes
    pip:
      name: docker-py

  - name: create gitlab config file
    become: yes
    template:
      src: gitconfig.j2
      dest: /etc/gitconfig
      mode: 0400

  - name: create config file
    become: yes
    template:
      src: config.json.j2
      dest: "{{ github_to_gitlab_host_conf_file }}"

  - name: create github-to-gitlab container
    become: yes
    docker_container:
      name: "github-to-gitlab"
      image: "mercury/github-to-gitlab:{{ github_to_gitlab_image_version }}"
      state: started
      command: "github2gitlab --mattermost-webhook-url {{ github_to_gitlab_mattermost_webhook_url }} --host 0.0.0.0"
      volumes:
        - "{{ github_to_gitlab_host_conf_file }}:/github-to-gitlab/config.json:ro"
        - "/etc/gitconfig:/etc/gitconfig:ro"
      published_ports:
        - "80:8080"
