---
  - name: create gitlab credentials
    become: yes
    copy:
      dest: ~/.git-credentials
      content: "{{ gitlab_auth_url }}"
      mode: 0400

  - name: create ssh authorized_keys
    become: yes
    copy:
      dest: ~/.ssh/authorized_keys
      content: "{{ gitlab_authorised_key }}"
      mode: 0400

  - name: create github2gitlab container
    become: yes
    docker_container:
      name: "mercury/github2gitlab:{{ github2gitlab_image_version }}"
      image: "github2gitlab"
      state: started
      command: "python -m github2gitlab --mattermost-webhook-url {{ mattermost_webhook_url }} --host 0.0.0.0"
      volumes:
        - "{{ github2gitlab_host_conf_file }}:/github-to-gitlab-hook/config.json:ro"
      published_ports:
        - "80:8080"
