---
  - name: create gitlab credentials
    become: yes
    copy:
      dest: ~/.git-credentials
      content: "{{ gitlab_auth_url }}"
      mode: 0400

  - name: create config file
    become: yes
    template:
      src: config.json.j2
      dest: "{{ github_to_gitlab_host_conf_file }}"

  - name: create github-to-gitlab container
    become: yes
    docker_container:
      name: "mercury/github-to-gitlab:{{ github_to_gitlab_image_version }}"
      image: "github-to-gitlab"
      state: started
      command: "github2gitlab --mattermost-webhook-url {{ mattermost_webhook_url }} --host 0.0.0.0"
      volumes:
        - "{{ github_to_gitlab_host_conf_file }}:/github-to-gitlab/config.json"
        - "~/.git-credentials:~/.git-credentials:ro"
      published_ports:
        - "80:8080"
