# Copyright (c) 2017 Genome Research Ltd.
#
# Author: Joshua C. Randall <jcrandall@alum.mit.edu>
#
# This file is part of hgi-systems.
#
# hgi-systems is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#
---

# file: arvados.yml

- import_playbook: hgi-preamble-playbook.yml

- hosts: arvados-ssos
  vars:
    arvados_PLAYBOOK_sso_data_mountpoint: /mnt/arvados-sso-db
    arvados_PLAYBOOK_attached_volume_device: "{{ tf_type_openstack_compute_instance_v2_GROUP_volume_device }}"
  tasks:
    - name: configure attached-openstack-volume for arvados sso database
      import_role:
        name: attached-openstack-volume
      vars:
        attached_openstack_volume_vg: arvados-sso-vg
        attached_openstack_volume_vols:
          - name: arvados-sso-data
            size: "{{ ((tf_type_openstack_compute_instance_v2_GROUP_volume_size | int) * 1024) - 4 }}M"
            fstype: xfs
            mountpoint: "{{ arvados_PLAYBOOK_sso_data_mountpoint }}"
        attached_openstack_volumes:
          - device: "{{ arvados_PLAYBOOK_attached_volume_device }}"
        attached_openstack_volume_fs_create_indicator_file: "{{ arvados_GROUP_s3_backup_restore_indicator_file }}"
    - name: setup s3 to backup sso data 
      import_role:
        name: s3-backup
      vars:
        ###############################################################################
        # Variables that have no defaults and must be set
        ###############################################################################
        s3_backup_s3_bucket: "{{ arvados_GROUP_backup_s3_backup_bucket }}"
        s3_backup_s3_host: "{{ arvados_GROUP_backup_s3_host }}"
        s3_backup_s3_access_key: "{{ arvados_GROUP_backup_s3_access_key }}"
        s3_backup_s3_secret_key: "{{ arvados_GROUP_backup_s3_secret_key }}"
        s3_backup_source_dir: "{{ arvados_PLAYBOOK_sso_data_mountpoint }}"
        s3_backup_dest_path: "arvados/{{ arvados_cluster_id }}/sso"
        ###############################################################################
        # Restore from s3 if if this file is present (then delete it)
        ###############################################################################
        s3_backup_restore_indicator_file: "{{ arvados_GROUP_s3_backup_restore_indicator_file }}"
        ###############################################################################
        # Pre/post tasks
        ###############################################################################
        s3_backup_before_task: "sudo -u postgres pg_dumpall > {{ arvados_PLAYBOOK_sso_data_mountpoint }}/sso-db.out"
    - name: configure arvados-sso
      import_role:
        name: arvados-sso
      vars:
        arvados_sso_data_dir: "{{ arvados_PLAYBOOK_sso_data_mountpoint }}"

- hosts: arvados-masters
  vars:
    arvados_PLAYBOOK_api_data_mountpoint: /mnt/arvados-api-db
    arvados_PLAYBOOK_attached_volume_device: "{{ tf_type_openstack_compute_instance_v2_GROUP_volume_device }}"
  tasks:
    - name: configure attached-openstack-volume for arvados api database
      import_role:
        name: attached-openstack-volume
      vars:
        attached_openstack_volume_vg: arvados-api-vg
        attached_openstack_volume_vols:
          - name: arvados-api-data
            size: "{{ ((tf_type_openstack_compute_instance_v2_GROUP_volume_size | int) * 1024) - 4 }}M"
            fstype: xfs
            mountpoint: "{{ arvados_PLAYBOOK_api_data_mountpoint }}"
        attached_openstack_volumes:
          - device: "{{ arvados_PLAYBOOK_attached_volume_device }}"
        attached_openstack_volume_fs_create_indicator_file: "{{ arvados_GROUP_s3_backup_restore_indicator_file }}"
    - name: setup s3 to backup api server data 
      import_role:
        name: s3-backup
      vars:
        ###############################################################################
        # Variables that have no defaults and must be set
        ###############################################################################
        s3_backup_s3_bucket: "{{ arvados_GROUP_backup_s3_backup_bucket }}"
        s3_backup_s3_host: "{{ arvados_GROUP_backup_s3_host }}"
        s3_backup_s3_access_key: "{{ arvados_GROUP_backup_s3_access_key }}"
        s3_backup_s3_secret_key: "{{ arvados_GROUP_backup_s3_secret_key }}"
        s3_backup_source_dir: "{{ arvados_PLAYBOOK_api_data_mountpoint }}"
        s3_backup_dest_path: "arvados/{{ arvados_cluster_id }}/api"
        ###############################################################################
        # Restore from s3 if if this file is present (then delete it)
        ###############################################################################
        s3_backup_restore_indicator_file: "{{ arvados_GROUP_s3_backup_restore_indicator_file }}"
        ###############################################################################
        ###############################################################################
        # Pre/post tasks
        ###############################################################################
        s3_backup_before_task: "sudo -u postgres pg_dumpall > {{ arvados_PLAYBOOK_api_data_mountpoint }}/api-db.out"
    - name: configure arvados-master
      import_role:
        name: arvados-master
      vars:
        arvados_master_api_data_dir: "{{ arvados_PLAYBOOK_api_data_mountpoint }}"

- hosts: arvados-keeps
  roles:
    - arvados-keep

- hosts: arvados-keepproxies
  roles:
    - arvados-keepproxy

- hosts: arvados-workbenches
  roles:
    - arvados-workbench

- hosts: arvados-shells
  roles:
    - arvados-shell

- hosts: arvados-compute-nodes
  roles:
    - arvados-compute-node

# non-host playbooks
- hosts: arvados-clusters
  gather_facts: no
  roles:
    - arvados-cluster

