---

# Check dynamic inventory and set dynamic groups and facts (must all be gather_facts: no)
- import_playbook: dynamic-inventory-sanity-check.yml
- import_playbook: set-facts.yml

# Configure critical ssh bastion host infrastructure before gathering facts
- import_playbook: ssh-gateways.yml

# set dynamic groups (and gather facts) as some arvados playbooks require them
- import_playbook: dynamic-groups.yml
