---

# Check dynamic inventory and set dynamic groups and facts (must all be gather_facts: no)
- import_playbook: dynamic-inventory-sanity-check.yml
- import_playbook: set-facts.yml

# Configure critical ssh bastion host infrastructure before gathering facts
- import_playbook: ssh-gateways.yml

- hosts: all:!non-hosts
  gather_facts: no
  tasks:
    - set_fact:
        hgi_preamble_playbook_ran: "{{ hgi_preamble_playbook_ran | default(false) }}"

    - set_fact:
        hgi_preamble_run_common: "{{ not (hgi_preamble_playbook_ran or (skip_common | default(false))) }}"

# Run common role
- hosts: all:!non-hosts:!noconf
  tasks:
    - include_role:
        name: common
        private: true
      when: hgi_preamble_run_common

# Run Docker role
- hosts: dockerers
  tasks:
    - block:
      - include_role:
          name: docker
          private: true

      - name: add mercury to docker group
        become: yes
        user:
          append: yes
          groups:
            - docker
          name: mercury

      when: hgi_preamble_run_common

# Set fact that hgi-preamble has been ran
- hosts: all:!non-hosts
  tasks:
    - set_fact:
        hgi_preamble_playbook_ran: true
