---

# Check dynamic inventory and set dynamic groups and facts (must all be gather_facts: no)
- import_playbook: dynamic-inventory-sanity-check.yml
- import_playbook: set-facts.yml

- hosts: all:!non-hosts
  gather_facts: no
  tasks:
    - name: contact bastion hosts just to say hello (N.B THIS IS CRITICAL TO PROPER FUNCTION LATER IN THE ANSIBLE INVOCATION)
      delegate_to: "{{ item | regex_replace('.*[@]') }}"
      run_once: true
      vars:
        ansible_user: "{{ item | regex_replace('[@].*') }}"
      command: hostname
      with_items: "{{ all_GROUP_hosts_inventory_hostnames | map('extract', hostvars) | selectattr('bastion_user', 'defined') | selectattr('bastion_host', 'defined') | list | json_query('[].join(`@`,[bastion_user,bastion_host])') | default([]) | unique | list }}"
      when: "hgi_preamble_playbook_bastion_connections_established is not defined"

    - set_fact:
        hgi_preamble_playbook_bastion_connections_established: yes

- hosts: all:!non-hosts
  gather_facts: no
  tasks:
    - set_fact:
        hgi_preamble_playbook_ran: "{{ hgi_preamble_playbook_ran | default(false) }}"

    - set_fact:
        hgi_preamble_run_common: "{{ not (hgi_preamble_playbook_ran or (skip_common | default(false))) }}"

# Run common role
- hosts: all:!non-hosts:!noconf
  tasks:
    - include_role:
        name: common
        private: true
      when: hgi_preamble_run_common

# Set fact that hgi-preamble has been ran
- hosts: all:!non-hosts
  tasks:
    - set_fact:
        hgi_preamble_playbook_ran: true
