# Copyright (c) 2017, 2018 Genome Research Ltd.
#
# Author: Joshua C. Randall <jcrandall@alum.mit.edu>
#
# This file is part of hgi-systems.
#
# hgi-systems is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#
---
# file: hgi-preamble-playbook.yml

# Check dynamic inventory and set dynamic groups and facts (must all be gather_facts: no)
- import_playbook: dynamic-inventory-sanity-check.yml
- import_playbook: set-facts.yml

# Make initial contact with bastion hosts
- hosts: all:!non-hosts
  gather_facts: no
  tasks:
    - include_role:
        name: establish_bastion_connections
      vars:
        establish_bastion_connections_hostnames: "{{ all_GROUP_hosts_inventory_hostnames }}"
      when: establish_bastion_connections_ROLE_FACT_ran is not defined

# Run common role
- hosts: all:!non-hosts:!noconf
  vars:
    hgi_preamble_run_common: "{{ not ((hgi_preamble_playbook_PLAYBOOK_FACT_ran is defined) or (skip_common | default(false))) }}"
  tasks:
    - include_role:
        name: common
        private: true
      when: hgi_preamble_run_common

# Set fact that hgi-preamble has been ran
- hosts: all:!non-hosts
  tasks:
    - set_fact:
        hgi_preamble_playbook_PLAYBOOK_FACT_ran: yes
