# Copyright (c) 2017 Genome Research Ltd.
#
# Author: Joshua C. Randall <jcrandall@alum.mit.edu>
#
# This file is part of hgi-systems.
#
# hgi-systems is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#
---
# file: set-facts.yml

# Set facts on all cloud resources so they will be expanded and referencable via hostvars
- hosts: cloud-resources
  gather_facts: no
  roles:
    - cloud-resource

# Set consul credentials facts for consul_kv lookups
- hosts: consul-credentials
  gather_facts: no
  vars:
    set_facts_PLAYBOOK_consul_credentials_creds_ansible_consul_token: "{{ consul_credentials_GROUP_creds['ansible'].token }}"
    set_facts_PLAYBOOK_consul_credentials_creds_ansible_consul_url: "http://{{ consul_credentials_GROUP_creds['ansible'].address }}"
  tasks:
   - name: set ansible consul token from credentials
     set_fact:
       set_facts_PLAYBOOK_ansible_consul_token: "{{ set_facts_PLAYBOOK_consul_credentials_creds_ansible_consul_token }}"
       set_facts_PLAYBOOK_ansible_consul_url: "{{ set_facts_PLAYBOOK_consul_credentials_creds_ansible_consul_url }}"
       set_facts_PLAYBOOK_ansible_consul_host: "{{ set_facts_PLAYBOOK_consul_credentials_creds_ansible_consul_url | urlsplit('hostname') }}"
       set_facts_PLAYBOOK_ansible_consul_port: "{{ set_facts_PLAYBOOK_consul_credentials_creds_ansible_consul_url | urlsplit('port') }}"
- hosts: all:!consul-credentials
  gather_facts: no
  tasks:
   - name: set ansible consul token from shell environment
     set_fact:
       set_facts_PLAYBOOK_ansible_consul_token: "{{ lookup('env', 'ANSIBLE_CONSUL_TOKEN') }}"
       set_facts_PLAYBOOK_ansible_consul_url: "{{ lookup('env', 'ANSIBLE_CONSUL_URL') }}"
       set_facts_PLAYBOOK_ansible_consul_host: "{{ lookup('env', 'ANSIBLE_CONSUL_URL') | urlsplit('hostname') }}"
       set_facts_PLAYBOOK_ansible_consul_port: "{{ lookup('env', 'ANSIBLE_CONSUL_URL') | urlsplit('port') }}"

