# Copyright (c) 2014, 2015, 2016, 2017 Genome Research Ltd.
#
# Author: Joshua C. Randall <jcrandall@alum.mit.edu>
#
# This file is part of hgi-systems.
#
# hgi-systems is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#
---
# file: site.yml

# Check dynamic inventory and set dynamic groups and facts (must all be gather_facts: no)
- include: dynamic-inventory-sanity-check.yml
- include: set-facts.yml

# Dump ssh extra args and control_path values for debugging
- hosts: all
  gather_facts: no
  - debug:
      var: ansible_ssh_extra_args
  - debug:
      var: control_path

# Configure critical ssh bastion host infrastructure before gathering facts
- include: ssh-gateways.yml

# Set dynamic groups (and gather facts)
- include: dynamic-groups.yml

# Set up non-host infrastructure
- include: gitlab-projects.yml

# When image-building, make sure we apply common role even if no other groups apply
- hosts: image-building
  roles:
    - common

# Playbooks that need nonroot host hgi infrastructure
- include: mesos-masters.yml
- include: zookeepers.yml
- include: marathoners.yml
- include: chronosians.yml
- include: mesos-slaves.yml
- include: bamboosians.yml

# We need consul-agents for DNS functionality
# some subsequent roles may not work if they 
# come before (I'm looking at you SLURM)
- include: consul.yml

# Playbooks that only support root hosts
- include: arvados.yml
- include: cookie-jars.yml
- include: cookie-monsters.yml
- include: dockerers.yml
- include: gitlab-runners.yml
- include: hailers.yml
- include: openstack-tenant-cleaners.yml
- include: spark.yml

