# Copyright (c) 2014 Genome Research Ltd.
#
# Author: Joshua C. Randall <jcrandall@alum.mit.edu>
#
# This file is part of hgi-systems.
#
# hgi-systems is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#
---
# file: site.yml

# Sanity check that dynamic inventories have run
- hosts: canaries
  gather_facts: no
  tasks:
    - assert:
        that: groups[item] is defined
        msg: "dynamic inventory does not appear to have run (group '{{ item }}' not present)"
      with_items: "{{ canary_groups }}"
      any_errors_fatal: yes


# Set up non-host infrastructure
- include: gitlab-projects.yml

# Create dynamic groups for hosts based on OS
- hosts: all:!non-hosts
  tasks:
    - group_by: key=os_{{ ansible_distribution }}-{{ ansible_distribution_version }} # e.g. "os_Ubuntu_14.04"
    - group_by: key=os_{{ ansible_distribution }} # e.g. "os_Ubuntu"
    - group_by: key=os_family_{{ ansible_os_family }} # e.g. "os_Debian"

# Set facts on all cloud resources so they will be expanded and referencable via hostvars
- hosts: cloud-resources
  gather_facts: no
  roles:
    - cloud-resource
    
# When image-building, make sure we apply common role even if no other groups apply
- hosts: image-building
  roles:
    - common

# Playbooks that need nonroot host hgi infrastructure
- include: mesos-masters.yml
- include: zookeepers.yml
- include: marathoners.yml
- include: chronosians.yml
- include: mesos-slaves.yml
- include: bamboosians.yml

# Playbooks that only support root hosts
- include: arvados.yml
- include: arvados-crunchers.yml
- include: consul-agents.yml
- include: consul-servers.yml
- include: cookie-jars.yml
- include: cookie-monsters.yml
- include: dockerers.yml
- include: gitlab-runners.yml
- include: hailers.yml
- include: openstack-tenant-cleaners.yml
- include: spark.yml

# Higher-level infrastructure built on top of hosts
- include: consul-clusters.yml
