openstack_instance_security_groups:
 - "{{ (groups['openstack-security-groups-ssh'] | map('extract', hostvars) | selectattr('openstack_tenant', 'equalto', openstack_tenant) | list())[0].openstack_name }}"
 - "{{ (groups['openstack-security-groups-docker-registry'] | map('extract', hostvars) | selectattr('openstack_tenant', 'equalto', openstack_tenant) | list())[0].openstack_name }}"

openstack_instance_flavor: m1.medium


