---

consul_s3_backup_bucket: consul-backup
consul_s3_host: "{{ s3_credentials['sanger-ceph-mercury']['s3_host'] }}"
consul_s3_access_key: "{{ s3_credentials['sanger-ceph-mercury']['s3_access_key'] }}"
consul_s3_secret_key: "{{ s3_credentials['sanger-ceph-mercury']['s3_secret_key'] }}"
