# Copyright (c) 2017 Genome Research Ltd.
#
# Authors: 
#   Colin Nolan <colin.nolan@sanger.ac.uk>
#   Joshua C. Randall <jcrandall@alum.mit.edu>
#
# This file is part of hgi-ansible.
#
# hgi-ansible is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#
---

consul_encrypt: "{{ consul_server_encrypt }}"

consul_bootstrap_expect: "{{ groups['consul-servers'] | count }}"
consul_advertise_address: "{{ hostvars[inventory_hostname]['openstack_servers'][0].public_v4 }}"

consul_acl_master_token: "{{ consul_server_acl_master_token }}"
consul_acl_default_policy: "deny"
consul_acl_datacenter: "{{ consul_datacenter }}"

consul_dns_allow_stale: true
consul_dns_max_stale: 30s
consul_dns_node_ttl: 30s
consul_dns_only_passing: true
consul_recursors: "{{ sanger_network_dns_servers }}"

consul_s3_backup_bucket: consul-backup
consul_s3_host: "{{ s3_credentials['sanger-ceph-mercury']['s3_host'] }}"
consul_s3_access_key: "{{ s3_credentials['sanger-ceph-mercury']['s3_access_key'] }}"
consul_s3_secret_key: "{{ s3_credentials['sanger-ceph-mercury']['s3_secret_key'] }}"
