- name: restart nginx
  become: yes
  systemd:
    name: nginx
    state: restarted

- name: restart runit
  become: yes
  systemd: 
    name: runit
    state: restarted

- name: restart arvados-keepproxy
  become: yes
  runit:
    name: arvados-keepproxy
    enabled: yes
    state: restarted
    service_dir: /etc/service
    service_src: /etc/sv
  notify:
   - restart runit

- name: restart arvados-keep-web
  become: yes
  runit:
    name: arvados-keep-web
    enabled: yes
    state: restarted
    service_dir: /etc/service
    service_src: /etc/sv
  notify:
   - restart runit


