arvados_keep_blob_signing_key_file: "/etc/arvados-keep-blob-signing.key"
arvados_keep_data_manager_token_file: "/etc/arvados-data-manager.token"
arvados_keep_s3_access_key_file: "/etc/arvados-keep-s3.access_key"
arvados_keep_s3_secret_key_file: "/etc/arvados-keep-s3.secret_key"
arvados_keep_blob_signature_ttl_s: 1209600
arvados_keep_max_buffers: 128
arvados_keep_trash_check_interval: "24h0m0s"
arvados_keep_trash_lifetime: "7d0h0m0s"
