- name: restart munge
  become: yes
  service:
    name: munge
    state: restarted
  listen: "reload slurm"

- name: reload slurmctld
  become: yes
  service:
    name: slurmctld
    state: reloaded
  listen: "reload slurm"
