# Copyright (c) 2014, 2016, 2017 Genome Research Ltd.
#
# Authors:
# * Joshua C. Randall <jcrandall@alum.mit.edu>
# * Christopher Harrison <ch12@sanger.ac.uk>
#
# This file is part of hgi-systems.
#
# hgi-systems is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#
---
# file: group_vars/all

###############################################################################
# Vault contains:
###############################################################################
#   all_GROUP_root_secret: |
#     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
#     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
#
###############################################################################

all_GROUP_apt_cache_valid_time: 86400
all_apt_cache_valid_time: "{{ all_GROUP_apt_cache_valid_time }}" # FIXME remove this after refactor

# FIXME: everything below should be namespaced into `all_` (or moved elsewhere)

hgi_conf_dir: "{{ hgi_dir }}/etc"
hgi_log_dir: "{{ hgi_dir }}/log"
hgi_pid_dir: "{{ hgi_dir }}/pid"
hgi_run_dir: "{{ hgi_dir }}/run"
hgi_certs_dir: "{{ hgi_conf_dir }}/certs"

hgi_cluster_name: "hgs4"

zookeeper_client_port: 2181

mesos_master_http_port: 5050
mesos_slave_http_port: 5051
mesos_master_service_port: 50040

marathon_local_port_min: 50100
marathon_local_port_max: 50999

marathon_http_port: 40050
marathon_service_port: 50050

chronos_http_port: 40060
chronos_service_port: 50060

bamboo_http_port: 40070
bamboo_service_port: 50070
bamboo_frontend_http_port: 50080

# FIXME? Do these have any place being here?...
sanger_http_proxy: http://wwwcache.sanger.ac.uk:3128
sanger_https_proxy: http://wwwcache.sanger.ac.uk:3128
sanger_ftp_proxy: http://wwwcache.sanger.ac.uk:3128

ansible_ssh_common_args: "{% if bastion_host is defined and bastion_host != '' and bastion_host != ansible_host %}-o ProxyCommand=\"ssh -W %h:%p -o StrictHostKeyChecking=no -q {% if bastion_user is defined and bastion_user != '' %}{{ bastion_user }}@{% endif %}{{ bastion_host }}\"{% endif %}"

control_path: "{% if bastion_host is defined and bastion_host != '' and bastion_host != ansible_host %}%(directory)s/ansible-ssh-{{ bastion_host }}-%%h-%%p-%%r{% else %}%(directory)s/ansible-ssh-direct-%%h-%%p-%%r{% endif %}"

pgp_keyserver_url: hkp://keyserver.ubuntu.com:80

all_GROUP_sanger_network_dns_servers:
  - 172.18.255.1
  - 172.18.255.2
  - 172.18.255.3

all_GROUP_env_ANSIBLE_CONSUL_TOKEN: "{{ lookup('env', 'ANSIBLE_CONSUL_TOKEN') }}"
