---

- name: add gitlab signing key
  tags: gitlab-runner
  become: yes
  apt_key:
    url: "https://packages.gitlab.com/gpg.key"
    state: present
  when: ansible_os_family == 'Debian'

- name: add gitlab apt repos
  tags: gitlab-runner
  become: yes
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items: "{{ gitlab_repos }}"
  when: ansible_os_family == 'Debian'

- name: install gitlab-runner and docker_container module prereqs (apt)
  tags: gitlab-runner
  become: yes
  apt: name={{ item }} state=present update_cache=yes cache_valid_time={{ apt_cache_valid_time }}
  with_items:
    - gitlab-ci-multi-runner=1.11.1 # pin to 1.11.1 until gitlab-ci-multi-runner is fixed or our gitlab is updated (https://gitlab.com/gitlab-org/gitlab-ci-multi-runner/issues/2305)
    - python-docker
    - python-pip
  when: ansible_os_family == 'Debian'

- name: install gitlab-runner module prereqs (pip)
  tags: gitlab-runner
  become: yes
  pip:
    name: python-gitlab

- name: create docker-machine CA cert directory
  tags:
    - gitlab-runner
  become: yes
  file: path=/root/.docker/machine/certs state=directory

- name: put previously generated docker-machine self-signed CA certs in place
  tags: gitlab-runner
  become: yes
  template:
    src: "{{ item }}.j2"
    dest: "/root/.docker/machine/certs/{{ item }}"
    owner: root
    mode: 0600
  with_items:
    - ca.pem
    - ca-key.pem
    - cert.pem
    - key.pem

- name: install gitlab runner ssh key (for docker machine)
  tags: gitlab-runner
  become: yes
  template:
    src: gitlab_runner_ssh_private_key.j2
    dest: "{{ gitlab_runner_ssh_private_key_file }}"
    owner: root
    mode: 0600

- name: ensure gitlab-runner S3 bucket exists
  tags:
    - gitlab-runner
    - s3
  delegate_to: localhost
  s3_bucket:
    ceph: yes
    s3_url: "{{ gitlab_runner_s3_endpoint }}"
    aws_access_key: "{{ gitlab_runner_s3_access_key }}"
    aws_secret_key: "{{ gitlab_runner_s3_secret_key }}"
    name: "{{ gitlab_runner_s3_bucket }}"
    state: present
