---

- name: create gitlab runner configuration fragment directory
  tags:
    - gitlab-runner
    - gitlab-runner-register
  become: yes
  file:
    path: /etc/gitlab-runner.d
    state: directory

- name: create gitlab runner configuration header fragment
  tags:
    - gitlab-runner
    - gitlab-runner-register
  become: yes
  template:
    src: 00config.toml.j2
    dest: /etc/gitlab-runner.d/00config.toml

- name: register gitlab runner
  tags:
    - gitlab-runner
    - gitlab-runner-register
  become: yes
  gitlab_ci_multi_runner_register:
    gitlab_url: "{{ gitlab_url }}"
    gitlab_token: "{{ gitlab_token }}"
    registration_url: "{{ item[1].url }}"
    registration_token: "{{ item[1].token }}"
    executor: "{{ item[0].executor }}"
    limit: "{{ item[0].limit }}"
    # FIXME: The below is a repeat of `gitlab_runner_descriptions`, which is dangerous if it is different
    description: "{{ item[0].name }}-{{ inventory_hostname_short }}"
    tags: "{{ group_names | union(item[0].extratags | default([])) | join(',') }}"
    extra_args: "{{ item[0].extraargs | default('') }}"
  with_nested:
    - "{{ gitlab_runner_registrations }}"
    - "{{ gitlab_runner_tokens }}"
  when: "not 'image-building' in group_names"

- name: assemble gitlab runner configuration
  tags:
    - gitlab-runner
    - gitlab-runner-register
  become: yes
  assemble: src=/etc/gitlab-runner.d dest=/etc/gitlab-runner/config.toml regexp=".*\.toml"git st
  when: "not 'image-building' in group_names"

- name: register gitlab project runner with projects
  tags:
    - gitlab-runner
    - gitlab-runner-register
  delegate_to: localhost
  gitlab_ci_project_runners:
    gitlab_url: "{{ gitlab_url }}"
    gitlab_project: "{{ item }}"
    gitlab_token: "{{ gitlab_token }}"
    gitlab_runners: "{{ gitlab_runner_descriptions }}"
  with_items: "{{ gitlab_runner_projects }}"
