---

- name: setup docker registry container
  tags: gitlab-runner
  become: yes
  docker_container:
    env:
      REGISTRY_PROXY_REMOTEURL: https://registry-1.docker.io
    published_ports: 6000:5000
    restart_policy: always
    name: registry
    image: registry:2
