---

docker:
  images:
    - name: mercury/gitlab-ci-git-push
      dockerfile: gitlab-ci-git-push/Dockerfile
      context: .
    - name: mercury/om
      dockerfile: om/Dockerfile
      context: .
    - name: mercury/os3
      dockerfile: os3/Dockerfile
      context: .
    - name: mercury/pao
      dockerfile: pao/Dockerfile
      context: .
    - name: mercury/spark-builder
      dockerfile: spark-builder/Dockerfile
      context: .
    - name: mercury/taos
      dockerfile: taos/Dockerfile
      context: .
    - name: mercury/taos-dev
      dockerfile: taos-dev/Dockerfile
      context: .
  registries:
    - url: "{{ env['CI_DOCKER_REGISTRY_URL'] }}"
      username: "{{ env['CI_DOCKER_REGISTRY_USERNAME'] }}"
      password: "{{ env['CI_DOCKER_REGISTRY_PASSWORD'] }}"

checksum_storage:
  type: consul
  url: "{{ env['CONSUL_HTTP_ADDR'] }}"
  token: "{{ env['CONSUL_HTTP_TOKEN'] }}"
  key: ci/docker-build-checksums
  lock: ci/docker-build-checksums.lock
