# Copyright (c) 2017 Genome Research Ltd.
#
# Author: Joshua C. Randall <jcrandall@alum.mit.edu>
#
# This file is part of hgi-systems.
#
# hgi-systems is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#
---
# file: roles/hail/meta/main.yml

dependencies:
  - role: common
  - role: wtsi-hgi.ansible-anaconda
    vars:
      anaconda_python_ver: 2
      anaconda_ver: "{{ hail_anaconda_version }}"
      anaconda_pkg_update: no
      anaconda_parent_dir: "{{ hail_anaconda_prefix_dir | dirname }}"
      anaconda_link_subdir: "{{ hail_anaconda_prefix_dir | basename }}"

  - role: spark
    vars:
      ###############################################################################
      # Variables that have no defaults and must be set
      ###############################################################################
      spark_ssh_key: "{{ hail_ssh_key }}"
      spark_ssl_cert: "{{ hail_master_cert }}"
      spark_ssl_key: "{{ hail_master_key }}"
      spark_master_host_list: "{{ hail_master_host_list }}"
      spark_worker_host_list: "{{ hail_computer_host_list }}"
      spark_master_external_hostname: "{{ hail_master_external_hostname }}"
      spark_master_external_domain: "{{ hail_master_external_domain }}"
      ###############################################################################
      # Versions
      ###############################################################################
      spark_version: "{{ hail_spark_version }}"
      spark_build_version: "{{ hail_spark_build_version }}"
      ###############################################################################
      # Source URL and checksum (use builds on Apache mirrors by default)
      ###############################################################################
      spark_tgz_url: "{{ hail_spark_tgz_url }}"
      spark_tgz_checksum: "{{ hail_spark_tgz_checksum }}"
      ###############################################################################
      # Directories and Paths
      ###############################################################################
      spark_prefix_dir: "/usr/local/spark-{{ hail_spark_build_version }}"
      #spark_ssl_key_file: /etc/ssl.key
      #spark_ssl_cert_file: /etc/ssl.cert
      ###############################################################################
      # Master server settings
      ###############################################################################
      #spark_master_server_name: "{{ spark_master_external_hostname }}.{{ spark_master_external_domain }}"
      #spark_master_backend_port: 8080
      ###############################################################################
      # Users/Groups
      ###############################################################################
      spark_user: "{{ hail_user }}"
      spark_group: "{{ hail_group }}"
      spark_authorized_keys: "{{ hail_authorized_keys }}"
      ###############################################################################
      # General settings
      ###############################################################################
      spark_apt_cache_valid_time: "{{ hail_apt_cache_valid_time }}"
