---

dependencies:
  - role: wtsi-hgi.ansible-anaconda
    vars:
      anaconda_python_ver: 2
      anaconda_ver: "{{ hail_anaconda_version }}"
      anaconda_pkg_update: no
      anaconda_parent_dir: "{{ hail_anaconda_installation_location | dirname }}"
      anaconda_link_subdir: "{{ hail_anaconda_installation_location | basename }}"

  - role: spark-master
    vars:
      spark_common_version: "{{ hail_spark_version }}"
      spark_common_prefix: "{{ hail_spark_home }}"
