# Copyright (c) 2017 Genome Research Ltd.
#
# Author: Joshua C. Randall <jcrandall@alum.mit.edu>
#
# This file is part of hgi-systems.
#
# hgi-systems is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#
---
# file: roles/hail/meta/main.yml

dependencies:
  - role: common
  - role: wtsi-hgi.ansible-anaconda
    vars:
      anaconda_python_ver: 2
      anaconda_ver: "{{ hail_anaconda_version }}"
      anaconda_pkg_update: no
      anaconda_parent_dir: "{{ hail_anaconda_prefix_dir | dirname }}"
      anaconda_link_subdir: "{{ hail_anaconda_prefix_dir | basename }}"

  - role: spark
    vars:
      spark_ssh_key: "{{ hail_ssh_key }}"
      spark_cert: "{{ hail_master_cert }}"
      spark_key: "{{ hail_master_key }}"
      spark_master_host_list: "{{ hail_master_host_list }}"
      spark_worker_host_list: "{{ hail_computer_host_list }}"
      spark_version: "{{ hail_spark_version }}"
      spark_tgz_url: "{{ hail_spark_tgz_url }}"
      spark_tgz_checksum: "{{ hail_spark_tgz_checksum }}"
      spark_master_external_hostname: "{{ hail_master_external_hostname }}"
      spark_master_external_domain: "{{ hail_master_external_domain }}"
