- name: restart nginx
  become: yes
  systemd:
    name: nginx
    state: restarted
    daemon_reload: yes

- name: restart haproxy
  become: yes
  systemd:
    name: haproxy
    state: restarted
    daemon_reload: yes

- name: restart rsyslog
  become: yes
  systemd:
    name: rsyslog
    state: restarted
    daemon_reload: yes
    
- name: restart netdata
  become: yes
  systemd:
    name: netdata
    state: restarted
    daemon_reload: yes

- name: restart runit
  become: yes
  systemd: 
    name: runit
    state: restarted
    daemon_reload: yes

- name: restart consul
  become: yes
  systemd:
    name: "{{ arvados_api_backend_consul_service_name }}"
    state: restarted
  when: "not 'image-building' in group_names"

